In [327]:
import pandas as pd

file_path = r"C:\Users\Isha\Downloads\CFL_External Data Pack_Phase1 (1).xlsx"

# Read with 2 header rows
df_actuals = pd.read_excel(file_path, sheet_name="Data Pack - Actual Bookings", header=[0,1])

# Flatten multi-level columns
df_actuals.columns = [
    (str(col[0]).strip() + "_" + str(col[1]).strip()).replace("Unnamed", "").strip("_")
    for col in df_actuals.columns
]

# Clean column names
df_actuals.columns = df_actuals.columns.str.replace("  ", " ").str.strip()

# Drop completely empty columns
df_actuals = df_actuals.dropna(axis=1, how='all')

# Preview
df_actuals.head()

,Cost Rank_: 0_level_1,Product Name_: 1_level_1,Product Life Cycle_: 2_level_1,ACTUAL UNITS_: 3_level_1,ACTUAL UNITS_: 4_level_1,ACTUAL UNITS_: 5_level_1,ACTUAL UNITS_: 6_level_1,ACTUAL UNITS_: 7_level_1,ACTUAL UNITS_: 8_level_1,ACTUAL UNITS_: 9_level_1,...,ACTUAL UNITS_: 12_level_1,ACTUAL UNITS_: 13_level_1,ACTUAL UNITS_: 14_level_1,Forecasted Units_Your Forecast FY26 Q2,Forecasted Units_Demand Planners' Forecast,Forecasted Units_Marketing Team's Forecast,Forecasted Units_Data Science Team's Forecast,Forecasted Units_Data Science Team's Forecast.1,Forecasted Units_Data Science Team's Forecast.2,Forecasted Units_Data Science Team's Forecast.3
0,NaN,NaN,NaN,FY23 Q2,FY23 Q3,FY23 Q4,FY24 Q1,FY24 Q2,FY24 Q3,FY24 Q4,...,FY25 Q3,FY25 Q4,FY26 Q1,FY26 Q2,NaN,NaN,NaN,NaN,NaN,NaN
1,1,SWITCH Enterprise 48-Port UPOE,Sustaining,21149,10584,16105,12434,9437,17530,18518,...,14395,18663,13144,NaN,15052.101882,14795.306069,17011.0,NaN,NaN,NaN
2,2,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,30498,40505,61214,41932,59424,60073,66952,...,87843,71494,58318,NaN,79000.0,66274.81571,79114.0,NaN,NaN,NaN
3,3,SWITCH Core 25G/100G Fiber,Sustaining,4680,4397,5065,4092,4573,5449,5801,...,5701,6784,6346,NaN,6620.962605,6739.907617,7861.0,NaN,NaN,NaN
4,4,SWITCH Enterprise 24-Port PoE+,Sustaining,10927,8358,11681,10461,9704,11345,9946,...,9436,10338,8433,NaN,9200.438118,10383.999801,9789.0,NaN,NaN,NaN

In [328]:
df_actuals.shape

(66, 22)

In [329]:
#dropping the forecast cols from df_actuals

In [330]:
# ==============================
# DROP FY26 Q2 FORECAST BLOCK
# ==============================

cols_to_drop = [col for col in df_actuals.columns if "forecasted units" in col.lower()]

df_actuals = df_actuals.drop(columns=cols_to_drop)

print("Dropped columns:", cols_to_drop)

df_actuals.head()

Dropped columns: ['Forecasted Units_Your Forecast FY26 Q2', "Forecasted Units_Demand Planners' Forecast", "Forecasted Units_Marketing Team's Forecast", "Forecasted Units_Data Science Team's Forecast", "Forecasted Units_Data Science Team's Forecast.1", "Forecasted Units_Data Science Team's Forecast.2", "Forecasted Units_Data Science Team's Forecast.3"]

,Cost Rank_: 0_level_1,Product Name_: 1_level_1,Product Life Cycle_: 2_level_1,ACTUAL UNITS_: 3_level_1,ACTUAL UNITS_: 4_level_1,ACTUAL UNITS_: 5_level_1,ACTUAL UNITS_: 6_level_1,ACTUAL UNITS_: 7_level_1,ACTUAL UNITS_: 8_level_1,ACTUAL UNITS_: 9_level_1,ACTUAL UNITS_: 10_level_1,ACTUAL UNITS_: 11_level_1,ACTUAL UNITS_: 12_level_1,ACTUAL UNITS_: 13_level_1,ACTUAL UNITS_: 14_level_1
0,NaN,NaN,NaN,FY23 Q2,FY23 Q3,FY23 Q4,FY24 Q1,FY24 Q2,FY24 Q3,FY24 Q4,FY25 Q1,FY25 Q2,FY25 Q3,FY25 Q4,FY26 Q1
1,1,SWITCH Enterprise 48-Port UPOE,Sustaining,21149,10584,16105,12434,9437,17530,18518,14710,16256,14395,18663,13144
2,2,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,30498,40505,61214,41932,59424,60073,66952,57131,78096,87843,71494,58318
3,3,SWITCH Core 25G/100G Fiber,Sustaining,4680,4397,5065,4092,4573,5449,5801,4868,5659,5701,6784,6346
4,4,SWITCH Enterprise 24-Port PoE+,Sustaining,10927,8358,11681,10461,9704,11345,9946,8461,8436,9436,10338,8433

In [331]:
#making df_forecasts from the data pack sheet

In [332]:
import pandas as pd

file_path = r"C:\Users\Isha\Downloads\CFL_External Data Pack_Phase1 (1).xlsx"

# ==============================
# 1. READ + FLATTEN
# ==============================

df = pd.read_excel(file_path, sheet_name="Data Pack - Actual Bookings", header=[0,1])

df.columns = [
    (str(col[0]).strip() + "_" + str(col[1]).strip()).replace("Unnamed", "").strip("_")
    for col in df.columns
]

df.columns = df.columns.str.strip()

# ==============================
# 2. FIND REQUIRED COLUMNS
# ==============================

cost_col = [col for col in df.columns if "cost rank" in col.lower()][0]
product_col = [col for col in df.columns if "product name" in col.lower()][0]
lifecycle_col = [col for col in df.columns if "life cycle" in col.lower()][0]

demand_col = [col for col in df.columns if "demand" in col.lower() and "forecast" in col.lower()][0]
marketing_col = [col for col in df.columns if "marketing" in col.lower()][0]
ds_col = [col for col in df.columns if "data science" in col.lower()][0]

# ==============================
# 3. CREATE CLEAN DATAFRAME
# ==============================

df_forecasts = df[[cost_col, product_col, lifecycle_col, demand_col, marketing_col, ds_col]].copy()

# ==============================
# 4. RENAME COLUMNS
# ==============================

df_forecasts.columns = [
    "cost_rank",
    "product",
    "life_cycle",
    "demand_forecast",
    "marketing_forecast",
    "data_science_forecast"
]

# ==============================
# 5. REMOVE EMPTY / HEADER ROWS
# ==============================

df_forecasts = df_forecasts[df_forecasts["cost_rank"].notna()]

# ==============================
# 6. FINAL OUTPUT
# ==============================

df_forecasts.head()
df_forecasts.shape

(61, 6)

In [333]:
df_forecasts.head()

,cost_rank,product,life_cycle,demand_forecast,marketing_forecast,data_science_forecast
1,1,SWITCH Enterprise 48-Port UPOE,Sustaining,15052.101882,14795.306069,17011.0
2,2,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,79000.0,66274.81571,79114.0
3,3,SWITCH Core 25G/100G Fiber,Sustaining,6620.962605,6739.907617,7861.0
4,4,SWITCH Enterprise 24-Port PoE+,Sustaining,9200.438118,10383.999801,9789.0
5,5,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,35588.0,44460.24672,49532.0

In [334]:
#making the big deals df

In [335]:
import pandas as pd

file_path =r"C:\Users\Isha\Downloads\CFL_External Data Pack_Phase1 (1).xlsx"

# ==============================
# 1. READ WITH MULTI-HEADER
# ==============================

df_big = pd.read_excel(file_path, sheet_name="Big Deal", header=[0,1])

# ==============================
# 2. FLATTEN COLUMNS
# ==============================

df_big.columns = [
    (str(col[0]).strip() + "_" + str(col[1]).strip()).replace("Unnamed", "").strip("_")
    for col in df_big.columns
]

df_big.columns = df_big.columns.str.strip()

# ==============================
# 3. IDENTIFY KEY COLUMNS
# ==============================

cost_col = [col for col in df_big.columns if "cost rank" in col.lower()][0]
product_col = [col for col in df_big.columns if "plid" in col.lower()][0]

# ==============================
# 4. KEEP ONLY BIG DEAL COLUMNS
# ==============================

bigdeal_cols = [
    col for col in df_big.columns 
    if "big deals" in col.lower()
]

# Final subset
df_big = df_big[[cost_col, product_col] + bigdeal_cols].copy()

# Rename keys
df_big = df_big.rename(columns={
    cost_col: "cost_rank",
    product_col: "product"
})

# ==============================
# 5. REMOVE INVALID ROWS
# ==============================

df_big = df_big[df_big["cost_rank"].notna()]

# ==============================
# 6. CONVERT WIDE → LONG
# ==============================

df_big_long = df_big.melt(
    id_vars=["cost_rank", "product"],
    var_name="quarter",
    value_name="big_deal"
)

# ==============================
# 7. CLEAN QUARTER COLUMN
# ==============================

df_big_long["quarter"] = df_big_long["quarter"].str.extract(r'(\d{4}Q\d)')

# ==============================
# 8. HANDLE MISSING VALUES
# ==============================

df_big_long["big_deal"] = pd.to_numeric(df_big_long["big_deal"], errors="coerce")
df_big_long["big_deal"] = df_big_long["big_deal"].fillna(0)

# ==============================
# 9. FINAL CLEANUP
# ==============================

df_big_long["cost_rank"] = df_big_long["cost_rank"].astype(int)

df_big_long = df_big_long.sort_values(by=["cost_rank", "quarter"])

# ==============================
# 10. OUTPUT
# ==============================

print(df_big_long.head())
print("Shape:", df_big_long.shape)

     cost_rank                         product quarter  big_deal
0            1  SWITCH Enterprise 48-Port UPOE  2024Q2       350
30           1  SWITCH Enterprise 48-Port UPOE  2024Q3      1334
60           1  SWITCH Enterprise 48-Port UPOE  2024Q4      2319
90           1  SWITCH Enterprise 48-Port UPOE  2025Q1       914
120          1  SWITCH Enterprise 48-Port UPOE  2025Q2      1950
Shape: (240, 4)

In [336]:
df_big_long.head()

     cost_rank                         product quarter  big_deal
0            1  SWITCH Enterprise 48-Port UPOE  2024Q2       350
30           1  SWITCH Enterprise 48-Port UPOE  2024Q3      1334
60           1  SWITCH Enterprise 48-Port UPOE  2024Q4      2319
90           1  SWITCH Enterprise 48-Port UPOE  2025Q1       914
120          1  SWITCH Enterprise 48-Port UPOE  2025Q2      1950

In [337]:
df_big_long.shape

(240, 4)

In [338]:
#making the scms df

In [339]:
import pandas as pd

file_path = r"C:\Users\Isha\Downloads\CFL_External Data Pack_Phase1 (1).xlsx"

# ==============================
# 1. READ + FLATTEN
# ==============================

df = pd.read_excel(file_path, sheet_name="SCMS", header=[0,1])

df.columns = [
    (str(col[0]).strip() + "_" + str(col[1]).strip()).replace("Unnamed", "").strip("_")
    for col in df.columns
]

df.columns = df.columns.str.strip()

# ==============================
# 2. IDENTIFY REQUIRED COLUMNS
# ==============================

cost_col = [col for col in df.columns if "cost rank" in col.lower()][0]
product_col = [col for col in df.columns if "plid" in col.lower()][0]
coverage_col = [col for col in df.columns if "coverage" in col.lower()][0]

# 🔥 IMPORTANT FIX: pick SCMS Units columns
scms_cols = [
    col for col in df.columns 
    if "scms units" in col.lower()
]

print("SCMS columns:", scms_cols)

# ==============================
# 3. CREATE DATAFRAME
# ==============================

df_scms = df[[cost_col, product_col, coverage_col] + scms_cols].copy()

# Rename
df_scms = df_scms.rename(columns={
    cost_col: "cost_rank",
    product_col: "product",
    coverage_col: "coverage"
})

# ==============================
# 4. REMOVE INVALID ROWS
# ==============================

df_scms = df_scms[df_scms["cost_rank"].notna()]

# ==============================
# 5. OUTPUT
# ==============================

print(df_scms.head())
print("Shape:", df_scms.shape)

SCMS columns: ['SCMS Units_: 3_level_1', 'SCMS Units_: 4_level_1', 'SCMS Units_: 5_level_1', 'SCMS Units_: 6_level_1', 'SCMS Units_: 7_level_1', 'SCMS Units_: 8_level_1', 'SCMS Units_: 9_level_1', 'SCMS Units_: 10_level_1', 'SCMS Units_: 11_level_1', 'SCMS Units_: 12_level_1', 'SCMS Units_: 13_level_1', 'SCMS Units_: 14_level_1', 'SCMS Units_: 15_level_1']
   cost_rank                         product          coverage  \
1        1.0  SWITCH Enterprise 48-Port UPOE        COMMERCIAL
2        1.0  SWITCH Enterprise 48-Port UPOE        ENTERPRISE
3        1.0  SWITCH Enterprise 48-Port UPOE             OTHER
4        1.0  SWITCH Enterprise 48-Port UPOE     PUBLIC SECTOR
5        1.0  SWITCH Enterprise 48-Port UPOE  SERVICE PROVIDER

  SCMS Units_: 3_level_1 SCMS Units_: 4_level_1 SCMS Units_: 5_level_1  \
1                 1583.5                   2570                   1481
2                 6329.5                 7274.5                   2531
3                   7009                   6310                   3381
4                   3597                   4658                   3899
5                   2650                    270                   -779

  SCMS Units_: 6_level_1 SCMS Units_: 7_level_1 SCMS Units_: 8_level_1  \
1                 2726.5                 955.16                 1216.4
2                 4107.5                2825.84                 2482.5
3                   3877                   5608                   3284
4                   5113                   2881                 1932.9
5                    110                     58                    414

  SCMS Units_: 9_level_1 SCMS Units_: 10_level_1 SCMS Units_: 11_level_1  \
1                   1576                    2347                    1244
2                 3448.5                    3683                  3835.6
3                   4619                    6400                    5275
4                   4331                    5284                  3357.4
5                   3446                     717                     840

  SCMS Units_: 12_level_1 SCMS Units_: 13_level_1 SCMS Units_: 14_level_1  \
1                 1888.25                  1373.5                    1990
2                 5856.45                    4716                  3720.4
3                    4797                    4438                    4619
4                  2861.8                    2895                  4684.6
5                     784                     802                    3512

  SCMS Units_: 15_level_1
1                937.9472
2               2983.0528
3                    4070
4                    3438
5                    1670
Shape: (174, 16)

In [340]:
df_scms.head(10)

,cost_rank,product,coverage,SCMS Units_: 3_level_1,SCMS Units_: 4_level_1,SCMS Units_: 5_level_1,SCMS Units_: 6_level_1,SCMS Units_: 7_level_1,SCMS Units_: 8_level_1,SCMS Units_: 9_level_1,SCMS Units_: 10_level_1,SCMS Units_: 11_level_1,SCMS Units_: 12_level_1,SCMS Units_: 13_level_1,SCMS Units_: 14_level_1,SCMS Units_: 15_level_1
1,1.0,SWITCH Enterprise 48-Port UPOE,COMMERCIAL,1583.5,2570,1481,2726.5,955.16,1216.4,1576,2347,1244,1888.25,1373.5,1990,937.9472
2,1.0,SWITCH Enterprise 48-Port UPOE,ENTERPRISE,6329.5,7274.5,2531,4107.5,2825.84,2482.5,3448.5,3683,3835.6,5856.45,4716,3720.4,2983.0528
3,1.0,SWITCH Enterprise 48-Port UPOE,OTHER,7009,6310,3381,3877,5608,3284,4619,6400,5275,4797,4438,4619,4070
4,1.0,SWITCH Enterprise 48-Port UPOE,PUBLIC SECTOR,3597,4658,3899,5113,2881,1932.9,4331,5284,3357.4,2861.8,2895,4684.6,3438
5,1.0,SWITCH Enterprise 48-Port UPOE,SERVICE PROVIDER,2650,270,-779,110,58,414,3446,717,840,784,802,3512,1670
6,1.0,SWITCH Enterprise 48-Port UPOE,SMB,77,64.5,74,166,105,110.2,107.5,93,155,70.5,170.5,137,46
7,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,COMMERCIAL,1215,3790.5,2861.55,6692.5,7083,4148,8116.5,8602,5313.5,8590.5,5668.5,5299.5,5776
8,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,ENTERPRISE,2094,3066.5,8388.95,7354,4517,12618.5,4766,7997.1,10581,6430,14848.25,9974,7945
9,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,OTHER,5128,6124,13211,14126,14685,18581,18246,24124,20091,35546,36144,27521,21778
10,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,PUBLIC SECTOR,13120,16081,15519,26622,15050.2144,25767.2856,28078,24269,19835,26196.63,30224.75,27571,22374

In [341]:
#making the vms df

In [342]:
#VMS Cleaning

In [343]:
import pandas as pd

file_path = r"C:\Users\Isha\Downloads\CFL_External Data Pack_Phase1 (1).xlsx"

# ==============================
# 1. READ + FLATTEN
# ==============================

df = pd.read_excel(file_path, sheet_name="VMS", header=[0,1])

df.columns = [
    (str(col[0]).strip() + "_" + str(col[1]).strip()).replace("Unnamed", "").strip("_")
    for col in df.columns
]

df.columns = df.columns.str.strip()

# ==============================
# 2. IDENTIFY REQUIRED COLUMNS
# ==============================

cost_col = [col for col in df.columns if "cost rank" in col.lower()][0]
product_col = [col for col in df.columns if "plid" in col.lower()][0]
vms_name_col = [col for col in df.columns if "vms top name" in col.lower()][0]

# 🔥 IMPORTANT: pick VMS Units columns
vms_cols = [
    col for col in df.columns 
    if "vms units" in col.lower()
]

print("VMS columns:", vms_cols)

# ==============================
# 3. CREATE DATAFRAME
# ==============================

df_vms = df[[cost_col, product_col, vms_name_col] + vms_cols].copy()

# Rename
df_vms = df_vms.rename(columns={
    cost_col: "cost_rank",
    product_col: "product",
    vms_name_col: "vms_category"
})

# ==============================
# 4. REMOVE INVALID ROWS
# ==============================

df_vms = df_vms[df_vms["cost_rank"].notna()]

# ==============================
# 5. OUTPUT
# ==============================

print(df_vms.head())
print("Shape:", df_vms.shape)

VMS columns: ['VMS Units_: 3_level_1', 'VMS Units_: 4_level_1', 'VMS Units_: 5_level_1', 'VMS Units_: 6_level_1', 'VMS Units_: 7_level_1', 'VMS Units_: 8_level_1', 'VMS Units_: 9_level_1', 'VMS Units_: 10_level_1', 'VMS Units_: 11_level_1', 'VMS Units_: 12_level_1', 'VMS Units_: 13_level_1', 'VMS Units_: 14_level_1', 'VMS Units_: 15_level_1']
   cost_rank                         product               vms_category  \
1        1.0  SWITCH Enterprise 48-Port UPOE  Education- Public/Private
2        1.0  SWITCH Enterprise 48-Port UPOE           Energy/Utilities
3        1.0  SWITCH Enterprise 48-Port UPOE         Financial Services
4        1.0  SWITCH Enterprise 48-Port UPOE                 Government
5        1.0  SWITCH Enterprise 48-Port UPOE                Health Care

  VMS Units_: 3_level_1 VMS Units_: 4_level_1 VMS Units_: 5_level_1  \
1                   618                  1090                  1024
2                   377                   413                   499
3                  1175                  2947                   959
4                  4579                  4994                  1827
5                  5269                  4463                  2137

  VMS Units_: 6_level_1 VMS Units_: 7_level_1 VMS Units_: 8_level_1  \
1                   834                   866                   583
2                   299                   500                   365
3                  1300                  1032                   946
4                  3762                  5377                  2059
5                  4334                  2266                  1820

  VMS Units_: 9_level_1 VMS Units_: 10_level_1 VMS Units_: 11_level_1  \
1                  1437                    664                    421
2                   345                    361                    649
3                  1173                   1568                   1065
4                  3320                   5709                   3438
5                  2550                   3162                   3499

  VMS Units_: 12_level_1 VMS Units_: 13_level_1 VMS Units_: 14_level_1  \
1                   1093                    646                   1078
2                    222                    244                    304
3                    936                   1688                   1060
4                   3021                   2488                   4111
5                   4353                   2807                   3060

  VMS Units_: 15_level_1
1                    618
2                    289
3                    738
4                   3682
5                   2253
Shape: (422, 16)

In [344]:
df_vms.head()

,cost_rank,product,vms_category,VMS Units_: 3_level_1,VMS Units_: 4_level_1,VMS Units_: 5_level_1,VMS Units_: 6_level_1,VMS Units_: 7_level_1,VMS Units_: 8_level_1,VMS Units_: 9_level_1,VMS Units_: 10_level_1,VMS Units_: 11_level_1,VMS Units_: 12_level_1,VMS Units_: 13_level_1,VMS Units_: 14_level_1,VMS Units_: 15_level_1
1,1.0,SWITCH Enterprise 48-Port UPOE,Education- Public/Private,618,1090,1024,834,866,583,1437,664,421,1093,646,1078,618
2,1.0,SWITCH Enterprise 48-Port UPOE,Energy/Utilities,377,413,499,299,500,365,345,361,649,222,244,304,289
3,1.0,SWITCH Enterprise 48-Port UPOE,Financial Services,1175,2947,959,1300,1032,946,1173,1568,1065,936,1688,1060,738
4,1.0,SWITCH Enterprise 48-Port UPOE,Government,4579,4994,1827,3762,5377,2059,3320,5709,3438,3021,2488,4111,3682
5,1.0,SWITCH Enterprise 48-Port UPOE,Health Care,5269,4463,2137,4334,2266,1820,2550,3162,3499,4353,2807,3060,2253

In [345]:
#converting the actual bookings to long format

In [346]:
df_actuals.head()

,Cost Rank_: 0_level_1,Product Name_: 1_level_1,Product Life Cycle_: 2_level_1,ACTUAL UNITS_: 3_level_1,ACTUAL UNITS_: 4_level_1,ACTUAL UNITS_: 5_level_1,ACTUAL UNITS_: 6_level_1,ACTUAL UNITS_: 7_level_1,ACTUAL UNITS_: 8_level_1,ACTUAL UNITS_: 9_level_1,ACTUAL UNITS_: 10_level_1,ACTUAL UNITS_: 11_level_1,ACTUAL UNITS_: 12_level_1,ACTUAL UNITS_: 13_level_1,ACTUAL UNITS_: 14_level_1
0,NaN,NaN,NaN,FY23 Q2,FY23 Q3,FY23 Q4,FY24 Q1,FY24 Q2,FY24 Q3,FY24 Q4,FY25 Q1,FY25 Q2,FY25 Q3,FY25 Q4,FY26 Q1
1,1,SWITCH Enterprise 48-Port UPOE,Sustaining,21149,10584,16105,12434,9437,17530,18518,14710,16256,14395,18663,13144
2,2,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,30498,40505,61214,41932,59424,60073,66952,57131,78096,87843,71494,58318
3,3,SWITCH Core 25G/100G Fiber,Sustaining,4680,4397,5065,4092,4573,5449,5801,4868,5659,5701,6784,6346
4,4,SWITCH Enterprise 24-Port PoE+,Sustaining,10927,8358,11681,10461,9704,11345,9946,8461,8436,9436,10338,8433

In [347]:
#dropping the forecasting col from df_actuals and storing it in df_actuals_clean

In [348]:
# ==============================
# DROP ALL FORECAST COLUMNS
# ==============================

df_actuals_clean = df_actuals[
    [col for col in df_actuals.columns if "forecast" not in col.lower()]
].copy()

# ==============================
# CHECK RESULT
# ==============================

print("Remaining columns:")
print(df_actuals_clean.columns)

df_actuals_clean.head()

Remaining columns:
Index(['Cost Rank_: 0_level_1', 'Product Name_: 1_level_1',
       'Product Life Cycle_: 2_level_1', 'ACTUAL UNITS_: 3_level_1',
       'ACTUAL UNITS_: 4_level_1', 'ACTUAL UNITS_: 5_level_1',
       'ACTUAL UNITS_: 6_level_1', 'ACTUAL UNITS_: 7_level_1',
       'ACTUAL UNITS_: 8_level_1', 'ACTUAL UNITS_: 9_level_1',
       'ACTUAL UNITS_: 10_level_1', 'ACTUAL UNITS_: 11_level_1',
       'ACTUAL UNITS_: 12_level_1', 'ACTUAL UNITS_: 13_level_1',
       'ACTUAL UNITS_: 14_level_1'],
      dtype='object')

,Cost Rank_: 0_level_1,Product Name_: 1_level_1,Product Life Cycle_: 2_level_1,ACTUAL UNITS_: 3_level_1,ACTUAL UNITS_: 4_level_1,ACTUAL UNITS_: 5_level_1,ACTUAL UNITS_: 6_level_1,ACTUAL UNITS_: 7_level_1,ACTUAL UNITS_: 8_level_1,ACTUAL UNITS_: 9_level_1,ACTUAL UNITS_: 10_level_1,ACTUAL UNITS_: 11_level_1,ACTUAL UNITS_: 12_level_1,ACTUAL UNITS_: 13_level_1,ACTUAL UNITS_: 14_level_1
0,NaN,NaN,NaN,FY23 Q2,FY23 Q3,FY23 Q4,FY24 Q1,FY24 Q2,FY24 Q3,FY24 Q4,FY25 Q1,FY25 Q2,FY25 Q3,FY25 Q4,FY26 Q1
1,1,SWITCH Enterprise 48-Port UPOE,Sustaining,21149,10584,16105,12434,9437,17530,18518,14710,16256,14395,18663,13144
2,2,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,30498,40505,61214,41932,59424,60073,66952,57131,78096,87843,71494,58318
3,3,SWITCH Core 25G/100G Fiber,Sustaining,4680,4397,5065,4092,4573,5449,5801,4868,5659,5701,6784,6346
4,4,SWITCH Enterprise 24-Port PoE+,Sustaining,10927,8358,11681,10461,9704,11345,9946,8461,8436,9436,10338,8433

In [349]:
df_actuals_clean.head()

,Cost Rank_: 0_level_1,Product Name_: 1_level_1,Product Life Cycle_: 2_level_1,ACTUAL UNITS_: 3_level_1,ACTUAL UNITS_: 4_level_1,ACTUAL UNITS_: 5_level_1,ACTUAL UNITS_: 6_level_1,ACTUAL UNITS_: 7_level_1,ACTUAL UNITS_: 8_level_1,ACTUAL UNITS_: 9_level_1,ACTUAL UNITS_: 10_level_1,ACTUAL UNITS_: 11_level_1,ACTUAL UNITS_: 12_level_1,ACTUAL UNITS_: 13_level_1,ACTUAL UNITS_: 14_level_1
0,NaN,NaN,NaN,FY23 Q2,FY23 Q3,FY23 Q4,FY24 Q1,FY24 Q2,FY24 Q3,FY24 Q4,FY25 Q1,FY25 Q2,FY25 Q3,FY25 Q4,FY26 Q1
1,1,SWITCH Enterprise 48-Port UPOE,Sustaining,21149,10584,16105,12434,9437,17530,18518,14710,16256,14395,18663,13144
2,2,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,30498,40505,61214,41932,59424,60073,66952,57131,78096,87843,71494,58318
3,3,SWITCH Core 25G/100G Fiber,Sustaining,4680,4397,5065,4092,4573,5449,5801,4868,5659,5701,6784,6346
4,4,SWITCH Enterprise 24-Port PoE+,Sustaining,10927,8358,11681,10461,9704,11345,9946,8461,8436,9436,10338,8433

In [350]:
#remooving the rows 32- 64 from the df_actuals_clean

In [351]:
df_actuals_clean = df_actuals_clean.drop(df_actuals_clean.index[32:64])

In [352]:
df_actuals_clean.tail()

,Cost Rank_: 0_level_1,Product Name_: 1_level_1,Product Life Cycle_: 2_level_1,ACTUAL UNITS_: 3_level_1,ACTUAL UNITS_: 4_level_1,ACTUAL UNITS_: 5_level_1,ACTUAL UNITS_: 6_level_1,ACTUAL UNITS_: 7_level_1,ACTUAL UNITS_: 8_level_1,ACTUAL UNITS_: 9_level_1,ACTUAL UNITS_: 10_level_1,ACTUAL UNITS_: 11_level_1,ACTUAL UNITS_: 12_level_1,ACTUAL UNITS_: 13_level_1,ACTUAL UNITS_: 14_level_1
29,29,SWITCH Industrial 24-Port PoE,Sustaining,NaN,NaN,1,48,57,115,155,270,305,445,646,301
30,30,ROUTER Branch 8-Port PoE,Sustaining,1259,1013,381,2364,974,1278,841,1026,1337,1634,2092,1208
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,29,SWITCH Industrial 24-Port PoE,0.594684,0.405316,0.464396,-0.535604,0.674157,-0.325843,NaN,0.817276,-0.182724,0.719814,-0.280186,0.451685,-0.548315
65,30,ROUTER Branch 8-Port PoE,0.68957,0.31043,0.770554,-0.229446,0.807834,-0.192166,NaN,0,2.062914,0.804971,0.195029,0,1.182295

In [353]:
df_actuals_clean.tail()

,Cost Rank_: 0_level_1,Product Name_: 1_level_1,Product Life Cycle_: 2_level_1,ACTUAL UNITS_: 3_level_1,ACTUAL UNITS_: 4_level_1,ACTUAL UNITS_: 5_level_1,ACTUAL UNITS_: 6_level_1,ACTUAL UNITS_: 7_level_1,ACTUAL UNITS_: 8_level_1,ACTUAL UNITS_: 9_level_1,ACTUAL UNITS_: 10_level_1,ACTUAL UNITS_: 11_level_1,ACTUAL UNITS_: 12_level_1,ACTUAL UNITS_: 13_level_1,ACTUAL UNITS_: 14_level_1
29,29,SWITCH Industrial 24-Port PoE,Sustaining,NaN,NaN,1,48,57,115,155,270,305,445,646,301
30,30,ROUTER Branch 8-Port PoE,Sustaining,1259,1013,381,2364,974,1278,841,1026,1337,1634,2092,1208
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,29,SWITCH Industrial 24-Port PoE,0.594684,0.405316,0.464396,-0.535604,0.674157,-0.325843,NaN,0.817276,-0.182724,0.719814,-0.280186,0.451685,-0.548315
65,30,ROUTER Branch 8-Port PoE,0.68957,0.31043,0.770554,-0.229446,0.807834,-0.192166,NaN,0,2.062914,0.804971,0.195029,0,1.182295

In [354]:
#converting the df_actuals_clean to df_actuals_long

In [355]:
df_actuals_clean.head()

,Cost Rank_: 0_level_1,Product Name_: 1_level_1,Product Life Cycle_: 2_level_1,ACTUAL UNITS_: 3_level_1,ACTUAL UNITS_: 4_level_1,ACTUAL UNITS_: 5_level_1,ACTUAL UNITS_: 6_level_1,ACTUAL UNITS_: 7_level_1,ACTUAL UNITS_: 8_level_1,ACTUAL UNITS_: 9_level_1,ACTUAL UNITS_: 10_level_1,ACTUAL UNITS_: 11_level_1,ACTUAL UNITS_: 12_level_1,ACTUAL UNITS_: 13_level_1,ACTUAL UNITS_: 14_level_1
0,NaN,NaN,NaN,FY23 Q2,FY23 Q3,FY23 Q4,FY24 Q1,FY24 Q2,FY24 Q3,FY24 Q4,FY25 Q1,FY25 Q2,FY25 Q3,FY25 Q4,FY26 Q1
1,1,SWITCH Enterprise 48-Port UPOE,Sustaining,21149,10584,16105,12434,9437,17530,18518,14710,16256,14395,18663,13144
2,2,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,30498,40505,61214,41932,59424,60073,66952,57131,78096,87843,71494,58318
3,3,SWITCH Core 25G/100G Fiber,Sustaining,4680,4397,5065,4092,4573,5449,5801,4868,5659,5701,6784,6346
4,4,SWITCH Enterprise 24-Port PoE+,Sustaining,10927,8358,11681,10461,9704,11345,9946,8461,8436,9436,10338,8433

In [356]:
# ==============================
# STEP 1: EXTRACT QUARTER NAMES
# ==============================

# Take first row (contains FY values)
quarter_row = df_actuals_clean.iloc[0]

# Convert to list
quarter_values = quarter_row.tolist()

# ------------------------------
# STEP 2: BUILD NEW COLUMN NAMES
# ------------------------------

new_columns = []

for i in range(len(df_actuals_clean.columns)):
    if i < 3:
        # Keep first 3 columns as is
        new_columns.append(df_actuals_clean.columns[i])
    else:
        # Replace with actual FY values
        new_columns.append(quarter_values[i])

# Assign new columns
df_actuals_clean.columns = new_columns

# Drop first row (it was header)
df_actuals_clean = df_actuals_clean[1:].reset_index(drop=True)

# ------------------------------
# STEP 3: MELT USING POSITIONS
# ------------------------------

df_actuals_long = df_actuals_clean.melt(
    id_vars=df_actuals_clean.columns[:3],   # first 3 columns
    value_vars=df_actuals_clean.columns[3:], # rest are quarters
    var_name="quarter",
    value_name="bookings"
)

# ------------------------------
# STEP 4: RENAME CLEANLY
# ------------------------------

df_actuals_long = df_actuals_long.rename(columns={
    df_actuals_long.columns[0]: "cost_rank",
    df_actuals_long.columns[1]: "product",
    df_actuals_long.columns[2]: "life_cycle"
})

# ------------------------------
# STEP 5: CLEAN VALUES
# ------------------------------

df_actuals_long["quarter"] = df_actuals_long["quarter"].astype(str).str.replace(" ", "")
df_actuals_long["bookings"] = pd.to_numeric(df_actuals_long["bookings"], errors="coerce")
df_actuals_long["cost_rank"] = pd.to_numeric(df_actuals_long["cost_rank"], errors="coerce")

# Drop empty rows
df_actuals_long = df_actuals_long.dropna(subset=["bookings"])

# Sort
df_actuals_long = df_actuals_long.sort_values(by=["cost_rank", "quarter"])



# ------------------------------
# FINAL OUTPUT
# ------------------------------

print(df_actuals_long.head())
print("Shape:", df_actuals_long.shape)

     cost_rank                         product  life_cycle quarter  bookings
0          1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  FY23Q2   21149.0
33         1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  FY23Q3   10584.0
66         1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  FY23Q4   16105.0
99         1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  FY24Q1   12434.0
132        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  FY24Q2    9437.0
Shape: (366, 5)

In [357]:
# ==============================
# FIX QUARTER COLUMN COMPLETELY
# ==============================

# Sort first (IMPORTANT)
df_actuals_long = df_actuals_long.sort_values(by=["cost_rank"]).reset_index(drop=True)

# Number of unique quarters per product
n_quarters = df_actuals_long.groupby("product")["quarter"].transform("count")

# Create correct quarter sequence (based on your data)
quarter_sequence = [
    "2023Q2","2023Q3","2023Q4",
    "2024Q1","2024Q2","2024Q3","2024Q4",
    "2025Q1","2025Q2","2025Q3","2025Q4",
    "2026Q1"
]

# Assign quarters per product
df_actuals_long["quarter"] = (
    df_actuals_long.groupby("product")
    .cumcount()
    .map(lambda x: quarter_sequence[x] if x < len(quarter_sequence) else None)
)

print(df_actuals_long.head())

   cost_rank                         product  life_cycle quarter  bookings
0        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q2   21149.0
1        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q3   10584.0
2        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q4   16105.0
3        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2024Q1   12434.0
4        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2024Q2    9437.0

In [358]:
df_actuals_long.shape

(366, 5)

In [359]:
df_actuals_long.head(100)

    cost_rank                         product  life_cycle quarter  bookings
0         1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q2   21149.0
1         1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q3   10584.0
2         1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q4   16105.0
3         1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2024Q1   12434.0
4         1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2024Q2    9437.0
..        ...                             ...         ...     ...       ...
95        9.0  SWITCH Enterprise 24-Port UPOE  Sustaining  2024Q3    2689.0
96        9.0  SWITCH Enterprise 24-Port UPOE  Sustaining  2024Q4    2963.0
97        9.0  SWITCH Enterprise 24-Port UPOE  Sustaining  2025Q1    3302.0
98        9.0  SWITCH Enterprise 24-Port UPOE  Sustaining  2025Q2    2309.0
99        9.0  SWITCH Enterprise 24-Port UPOE  Sustaining  2025Q3    2160.0

[100 rows x 5 columns]

In [360]:
df_actuals_long = df_actuals_long.sort_values(by=["cost_rank", "product", "quarter"])

In [361]:
df_actuals_long.head()

   cost_rank                         product  life_cycle quarter  bookings
0        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q2   21149.0
1        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q3   10584.0
2        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q4   16105.0
3        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2024Q1   12434.0
4        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2024Q2    9437.0

In [362]:
df_big_long.head()

     cost_rank                         product quarter  big_deal
0            1  SWITCH Enterprise 48-Port UPOE  2024Q2       350
30           1  SWITCH Enterprise 48-Port UPOE  2024Q3      1334
60           1  SWITCH Enterprise 48-Port UPOE  2024Q4      2319
90           1  SWITCH Enterprise 48-Port UPOE  2025Q1       914
120          1  SWITCH Enterprise 48-Port UPOE  2025Q2      1950

In [363]:
# df_actuals_long has been made 
#df_big_long is already in long format

In [364]:
# making long format of df_scms

In [365]:
df_scms.head()

,cost_rank,product,coverage,SCMS Units_: 3_level_1,SCMS Units_: 4_level_1,SCMS Units_: 5_level_1,SCMS Units_: 6_level_1,SCMS Units_: 7_level_1,SCMS Units_: 8_level_1,SCMS Units_: 9_level_1,SCMS Units_: 10_level_1,SCMS Units_: 11_level_1,SCMS Units_: 12_level_1,SCMS Units_: 13_level_1,SCMS Units_: 14_level_1,SCMS Units_: 15_level_1
1,1.0,SWITCH Enterprise 48-Port UPOE,COMMERCIAL,1583.5,2570,1481,2726.5,955.16,1216.4,1576,2347,1244,1888.25,1373.5,1990,937.9472
2,1.0,SWITCH Enterprise 48-Port UPOE,ENTERPRISE,6329.5,7274.5,2531,4107.5,2825.84,2482.5,3448.5,3683,3835.6,5856.45,4716,3720.4,2983.0528
3,1.0,SWITCH Enterprise 48-Port UPOE,OTHER,7009,6310,3381,3877,5608,3284,4619,6400,5275,4797,4438,4619,4070
4,1.0,SWITCH Enterprise 48-Port UPOE,PUBLIC SECTOR,3597,4658,3899,5113,2881,1932.9,4331,5284,3357.4,2861.8,2895,4684.6,3438
5,1.0,SWITCH Enterprise 48-Port UPOE,SERVICE PROVIDER,2650,270,-779,110,58,414,3446,717,840,784,802,3512,1670

In [366]:
# ==============================
# STEP 2: SCMS → LONG (FIXED)
# ==============================

# 1. Identify ID columns
id_cols = ["cost_rank", "product", "coverage"]

# 2. Value columns
value_cols = [col for col in df_scms.columns if col not in id_cols]

# 🔥 3. Create quarter mapping manually
quarters = [
    "2023Q1","2023Q2","2023Q3","2023Q4",
    "2024Q1","2024Q2","2024Q3","2024Q4",
    "2025Q1","2025Q2","2025Q3","2025Q4",
    "2026Q1"
]

# 4. MELT
df_scms_long = df_scms.melt(
    id_vars=id_cols,
    value_vars=value_cols,
    var_name="temp",
    value_name="scms"
)

# 5. Assign correct quarter using order
df_scms_long["quarter"] = df_scms_long.groupby(
    ["cost_rank", "product", "coverage"]
).cumcount().map(lambda x: quarters[x])

# ==============================
# 6. CLEAN VALUES
# ==============================

df_scms_long["scms"] = pd.to_numeric(df_scms_long["scms"], errors="coerce").fillna(0)

# ==============================
# 7. AGGREGATE
# ==============================

df_scms_long = df_scms_long.groupby(
    ["cost_rank", "product", "quarter"],
    as_index=False
)["scms"].sum()

# ==============================
# 8. OUTPUT
# ==============================

print(df_scms_long.head())
print("Shape:", df_scms_long.shape)

   cost_rank                         product quarter     scms
0        1.0  SWITCH Enterprise 48-Port UPOE  2023Q1  21246.0
1        1.0  SWITCH Enterprise 48-Port UPOE  2023Q2  21147.0
2        1.0  SWITCH Enterprise 48-Port UPOE  2023Q3  10587.0
3        1.0  SWITCH Enterprise 48-Port UPOE  2023Q4  16100.0
4        1.0  SWITCH Enterprise 48-Port UPOE  2024Q1  12433.0
Shape: (377, 4)

In [367]:
df_scms_long.head()

   cost_rank                         product quarter     scms
0        1.0  SWITCH Enterprise 48-Port UPOE  2023Q1  21246.0
1        1.0  SWITCH Enterprise 48-Port UPOE  2023Q2  21147.0
2        1.0  SWITCH Enterprise 48-Port UPOE  2023Q3  10587.0
3        1.0  SWITCH Enterprise 48-Port UPOE  2023Q4  16100.0
4        1.0  SWITCH Enterprise 48-Port UPOE  2024Q1  12433.0

In [368]:
#make the long format of df_long and aggregate it

In [369]:
# ==============================
# STEP 3: VMS → LONG FORMAT
# ==============================

# 1. Identify ID columns
id_cols = ["cost_rank", "product", "vms_category"]

# 2. Value columns
value_cols = [col for col in df_vms.columns if col not in id_cols]

# 🔥 3. Quarter mapping (same as SCMS)
quarters = [
    "2023Q1","2023Q2","2023Q3","2023Q4",
    "2024Q1","2024Q2","2024Q3","2024Q4",
    "2025Q1","2025Q2","2025Q3","2025Q4",
    "2026Q1"
]

# 4. MELT
df_vms_long = df_vms.melt(
    id_vars=id_cols,
    value_vars=value_cols,
    var_name="temp",
    value_name="vms"
)

# 5. Assign correct quarter using order
df_vms_long["quarter"] = df_vms_long.groupby(
    ["cost_rank", "product", "vms_category"]
).cumcount().map(lambda x: quarters[x])

# ==============================
# 6. CLEAN VALUES
# ==============================

df_vms_long["vms"] = pd.to_numeric(df_vms_long["vms"], errors="coerce").fillna(0)

# ==============================
# 7. AGGREGATE (IMPORTANT)
# ==============================

df_vms_long = df_vms_long.groupby(
    ["cost_rank", "product", "quarter"],
    as_index=False
)["vms"].sum()

# ==============================
# 8. SORT
# ==============================

df_vms_long = df_vms_long.sort_values(by=["cost_rank", "quarter"])

# ==============================
# 9. OUTPUT
# ==============================

print(df_vms_long.head())
print("Shape:", df_vms_long.shape)

   cost_rank                         product quarter      vms
0        1.0  SWITCH Enterprise 48-Port UPOE  2023Q1  21246.0
1        1.0  SWITCH Enterprise 48-Port UPOE  2023Q2  21147.0
2        1.0  SWITCH Enterprise 48-Port UPOE  2023Q3  10587.0
3        1.0  SWITCH Enterprise 48-Port UPOE  2023Q4  16100.0
4        1.0  SWITCH Enterprise 48-Port UPOE  2024Q1  12433.0
Shape: (377, 4)

In [370]:
df_vms_long.head()

   cost_rank                         product quarter      vms
0        1.0  SWITCH Enterprise 48-Port UPOE  2023Q1  21246.0
1        1.0  SWITCH Enterprise 48-Port UPOE  2023Q2  21147.0
2        1.0  SWITCH Enterprise 48-Port UPOE  2023Q3  10587.0
3        1.0  SWITCH Enterprise 48-Port UPOE  2023Q4  16100.0
4        1.0  SWITCH Enterprise 48-Port UPOE  2024Q1  12433.0

In [371]:
df_actuals_long.head()

   cost_rank                         product  life_cycle quarter  bookings
0        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q2   21149.0
1        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q3   10584.0
2        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q4   16105.0
3        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2024Q1   12434.0
4        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2024Q2    9437.0

In [372]:
print(df_actuals_long["quarter"].unique())
print(df_scms_long["quarter"].unique())

['2023Q2' '2023Q3' '2023Q4' '2024Q1' '2024Q2' '2024Q3' '2024Q4' '2025Q1'
 '2025Q2' '2025Q3' '2025Q4' '2026Q1' None]
['2023Q1' '2023Q2' '2023Q3' '2023Q4' '2024Q1' '2024Q2' '2024Q3' '2024Q4'
 '2025Q1' '2025Q2' '2025Q3' '2025Q4' '2026Q1']

In [373]:
df_actuals_long.head()

   cost_rank                         product  life_cycle quarter  bookings
0        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q2   21149.0
1        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q3   10584.0
2        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2023Q4   16105.0
3        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2024Q1   12434.0
4        1.0  SWITCH Enterprise 48-Port UPOE  Sustaining  2024Q2    9437.0

In [374]:
df_big_long.head()

     cost_rank                         product quarter  big_deal
0            1  SWITCH Enterprise 48-Port UPOE  2024Q2       350
30           1  SWITCH Enterprise 48-Port UPOE  2024Q3      1334
60           1  SWITCH Enterprise 48-Port UPOE  2024Q4      2319
90           1  SWITCH Enterprise 48-Port UPOE  2025Q1       914
120          1  SWITCH Enterprise 48-Port UPOE  2025Q2      1950

In [375]:
df_scms_long.head()

   cost_rank                         product quarter     scms
0        1.0  SWITCH Enterprise 48-Port UPOE  2023Q1  21246.0
1        1.0  SWITCH Enterprise 48-Port UPOE  2023Q2  21147.0
2        1.0  SWITCH Enterprise 48-Port UPOE  2023Q3  10587.0
3        1.0  SWITCH Enterprise 48-Port UPOE  2023Q4  16100.0
4        1.0  SWITCH Enterprise 48-Port UPOE  2024Q1  12433.0

In [376]:
df_vms_long.head()

   cost_rank                         product quarter      vms
0        1.0  SWITCH Enterprise 48-Port UPOE  2023Q1  21246.0
1        1.0  SWITCH Enterprise 48-Port UPOE  2023Q2  21147.0
2        1.0  SWITCH Enterprise 48-Port UPOE  2023Q3  10587.0
3        1.0  SWITCH Enterprise 48-Port UPOE  2023Q4  16100.0
4        1.0  SWITCH Enterprise 48-Port UPOE  2024Q1  12433.0

In [378]:
df_actuals_long.shape

(366, 5)

In [379]:
df_big_long.shape

(240, 4)

In [380]:
df_scms_long.shape

(377, 4)

In [381]:
df_vms_long.shape

(377, 4)

In [382]:
#merging for master table

In [383]:
# ==============================
# STEP 1: CLEAN KEYS (IMPORTANT)
# ==============================

for df in [df_actuals_long, df_big_long, df_scms_long, df_vms_long]:
    df["product"] = df["product"].astype(str).str.strip()
    df["quarter"] = df["quarter"].astype(str).str.strip()
    df["cost_rank"] = pd.to_numeric(df["cost_rank"], errors="coerce")

# ==============================
# STEP 2: START WITH ACTUALS
# ==============================

df_master = df_actuals_long.copy()

# ==============================
# STEP 3: MERGE BIG DEAL
# ==============================

df_master = df_master.merge(
    df_big_long,
    on=["cost_rank", "product", "quarter"],
    how="left"
)

# ==============================
# STEP 4: MERGE SCMS
# ==============================

df_master = df_master.merge(
    df_scms_long,
    on=["cost_rank", "product", "quarter"],
    how="left"
)

# ==============================
# STEP 5: MERGE VMS
# ==============================

df_master = df_master.merge(
    df_vms_long,
    on=["cost_rank", "product", "quarter"],
    how="left"
)

# ==============================
# STEP 6: FILL MISSING VALUES
# ==============================

df_master["big_deal"] = df_master["big_deal"].fillna(0)
df_master["scms"] = df_master["scms"].fillna(0)
df_master["vms"] = df_master["vms"].fillna(0)

# ==============================
# STEP 7: FINAL SORT
# ==============================

df_master = df_master.sort_values(by=["product", "quarter"]).reset_index(drop=True)

# ==============================
# OUTPUT
# ==============================

print(df_master.head())
print(df_master.shape)

   cost_rank              product life_cycle quarter  bookings  big_deal  \
0       25.0  IP CONFERENCE PHONE    Decline  2023Q2    4828.0       0.0
1       25.0  IP CONFERENCE PHONE    Decline  2023Q3    3853.0       0.0
2       25.0  IP CONFERENCE PHONE    Decline  2023Q4    5124.0       0.0
3       25.0  IP CONFERENCE PHONE    Decline  2024Q1    3486.0       0.0
4       25.0  IP CONFERENCE PHONE    Decline  2024Q2    3747.0    1275.0

     scms     vms
0  5124.0  5124.0
1  3486.0  3486.0
2  4128.0  4128.0
3  5786.0  5786.0
4  4866.0  4866.0
(366, 8)

In [384]:
df_master.head(30)

,cost_rank,product,life_cycle,quarter,bookings,big_deal,scms,vms
0,25.0,IP CONFERENCE PHONE,Decline,2023Q2,4828.0,0.0,5124.0,5124.0
1,25.0,IP CONFERENCE PHONE,Decline,2023Q3,3853.0,0.0,3486.0,3486.0
2,25.0,IP CONFERENCE PHONE,Decline,2023Q4,5124.0,0.0,4128.0,4128.0
3,25.0,IP CONFERENCE PHONE,Decline,2024Q1,3486.0,0.0,5786.0,5786.0
4,25.0,IP CONFERENCE PHONE,Decline,2024Q2,3747.0,1275.0,4866.0,4866.0
5,25.0,IP CONFERENCE PHONE,Decline,2024Q3,4516.0,0.0,4039.0,4039.0
6,25.0,IP CONFERENCE PHONE,Decline,2024Q4,7708.0,159.0,3277.0,3277.0
7,25.0,IP CONFERENCE PHONE,Decline,2025Q1,3277.0,1667.0,7708.0,7708.0
8,25.0,IP CONFERENCE PHONE,Decline,2025Q2,4039.0,750.0,4828.0,4828.0
9,25.0,IP CONFERENCE PHONE,Decline,2025Q3,4866.0,0.0,3853.0,3853.0
10,25.0,IP CONFERENCE PHONE,Decline,2025Q4,5786.0,725.0,4516.0,4516.0
11,25.0,IP CONFERENCE PHONE,Decline,2026Q1,4128.0,1488.0,3747.0,3747.0
12,22.0,IP PHONE Enterprise Desk,Decline,2023Q2,43403.0,0.0,32314.0,32314.0
13,22.0,IP PHONE Enterprise Desk,Decline,2023Q3,32314.0,0.0,43403.0,43403.0
14,22.0,IP PHONE Enterprise Desk,Decline,2023Q4,30180.0,0.0,41773.0,41773.0
15,22.0,IP PHONE Enterprise Desk,Decline,2024Q1,24936.0,0.0,28746.0,28746.0
16,22.0,IP PHONE Enterprise Desk,Decline,2024Q2,33754.0,0.0,40155.0,40155.0
17,22.0,IP PHONE Enterprise Desk,Decline,2024Q3,40155.0,7500.0,33754.0,33754.0
18,22.0,IP PHONE Enterprise Desk,Decline,2024Q4,28746.0,6108.0,24936.0,24936.0
19,22.0,IP PHONE Enterprise Desk,Decline,2025Q1,41773.0,0.0,30180.0,30180.0
20,22.0,IP PHONE Enterprise Desk,Decline,2025Q2,13465.0,10000.0,24413.0,24413.0
21,22.0,IP PHONE Enterprise Desk,Decline,2025Q3,18955.0,7602.0,21567.0,21567.0
22,22.0,IP PHONE Enterprise Desk,Decline,2025Q4,24413.0,0.0,18955.0,18955.0
23,22.0,IP PHONE Enterprise Desk,Decline,2026Q1,21567.0,4500.0,13465.0,13465.0
24,23.0,ROUTER Branch 4-Port PoE,Decline,2023Q2,10420.0,0.0,4486.0,4486.0
25,23.0,ROUTER Branch 4-Port PoE,Decline,2023Q3,4486.0,0.0,10420.0,10420.0
26,23.0,ROUTER Branch 4-Port PoE,Decline,2023Q4,3007.0,0.0,11120.0,11120.0
27,23.0,ROUTER Branch 4-Port PoE,Decline,2024Q1,11120.0,0.0,3007.0,3007.0
28,23.0,ROUTER Branch 4-Port PoE,Decline,2024Q2,8541.0,2205.0,5776.0,5776.0
29,23.0,ROUTER Branch 4-Port PoE,Decline,2024Q3,5776.0,0.0,8541.0,8541.0

In [221]:
df_master.head()

,cost_rank,product,life_cycle,quarter,bookings,big_deal,scms,vms
0,25,IP CONFERENCE PHONE,Decline,2023Q2,5124.0,0.0,5124.0,5124.0
1,25,IP CONFERENCE PHONE,Decline,2023Q3,3486.0,0.0,3486.0,3486.0
2,25,IP CONFERENCE PHONE,Decline,2023Q4,4828.0,0.0,4128.0,4128.0
3,25,IP CONFERENCE PHONE,Decline,2024Q1,3277.0,0.0,5786.0,5786.0
4,25,IP CONFERENCE PHONE,Decline,2024Q2,4516.0,1275.0,4866.0,4866.0

In [393]:
df_master.shape

(366, 12)

In [ ]:
#everything is okay till here

In [222]:
#time based features - quarter number

In [387]:
df_master["quarter_num"] = (
    df_master["quarter"]
    .astype(str)
    .str.extract(r'Q(\d)', expand=False)
    .astype(float)
    .astype("Int64")   # safe integer (handles NaN)
)

In [389]:
df_master.head()

,cost_rank,product,life_cycle,quarter,bookings,big_deal,scms,vms,quarter_num
0,25.0,IP CONFERENCE PHONE,Decline,2023Q2,4828.0,0.0,5124.0,5124.0,2
1,25.0,IP CONFERENCE PHONE,Decline,2023Q3,3853.0,0.0,3486.0,3486.0,3
2,25.0,IP CONFERENCE PHONE,Decline,2023Q4,5124.0,0.0,4128.0,4128.0,4
3,25.0,IP CONFERENCE PHONE,Decline,2024Q1,3486.0,0.0,5786.0,5786.0,1
4,25.0,IP CONFERENCE PHONE,Decline,2024Q2,3747.0,1275.0,4866.0,4866.0,2

In [225]:
# time trend

In [226]:
df_master = df_master.sort_values(["cost_rank", "quarter"])
df_master["time_index"] = df_master.groupby("cost_rank").cumcount()

In [231]:
# big deal indicator - buisness feature

In [390]:
df_master["has_bigdeal"] = (df_master["big_deal"] > 0).astype(int)

In [392]:
df_master["rolling_mean_3"] = (
    df_master.groupby("cost_rank")["bookings"]
    .transform(lambda x: x.rolling(3, min_periods=1).mean())
)

df_master["rolling_std_3"] = (
    df_master.groupby("cost_rank")["bookings"]
    .transform(lambda x: x.rolling(3, min_periods=1).std())
)

In [394]:
df_master.tail(30)

,cost_rank,product,life_cycle,quarter,bookings,big_deal,scms,vms,quarter_num,has_bigdeal,rolling_mean_3,rolling_std_3
336,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2023Q4,55237.0,0.0,55238.0,55238.0,4,0,46649.666667,7483.244239
337,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2024Q1,53599.0,0.0,53599.0,53599.0,1,0,50674.666667,6535.165976
338,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2024Q2,53108.0,14871.0,53108.0,53108.0,2,1,53981.333333,1114.806859
339,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2024Q3,51781.0,5872.0,51781.0,51781.0,3,1,52829.333333,940.490475
340,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2024Q4,84349.0,8789.0,59560.0,59560.0,4,1,63079.333333,18432.017587
341,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2025Q1,67670.0,10896.0,53245.0,53245.0,1,1,67933.333333,16285.596837
342,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2025Q2,60281.0,5581.0,60281.0,60281.0,2,1,70766.666667,12329.199663
343,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2025Q3,53710.0,8547.0,53710.0,53710.0,3,1,60553.666667,6983.993151
344,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2025Q4,59560.0,7447.0,41524.0,41524.0,4,1,57850.333333,3603.710634
345,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2026Q1,53245.0,7523.0,43188.0,43188.0,1,1,55505.000000,3519.421117
346,14.0,WIRELESS ACCESS POINT WiFi6E (External Antenna...,Sustaining,2023Q2,3711.0,0.0,0.0,0.0,2,0,3711.000000,NaN
347,14.0,WIRELESS ACCESS POINT WiFi6E (External Antenna...,Sustaining,2023Q3,5183.0,0.0,0.0,0.0,3,0,4447.000000,1040.861182
348,14.0,WIRELESS ACCESS POINT WiFi6E (External Antenna...,Sustaining,2023Q4,2219.0,0.0,0.0,0.0,4,0,3704.333333,1482.011246
349,14.0,WIRELESS ACCESS POINT WiFi6E (External Antenna...,Sustaining,2024Q1,3191.0,0.0,0.0,0.0,1,0,3531.000000,1510.967902
350,14.0,WIRELESS ACCESS POINT WiFi6E (External Antenna...,Sustaining,2024Q2,5730.0,378.0,498.0,498.0,2,1,3713.333333,1812.844266
351,14.0,WIRELESS ACCESS POINT WiFi6E (External Antenna...,Sustaining,2024Q3,7719.0,75.0,524.0,524.0,3,1,5546.666667,2269.560383
352,14.0,WIRELESS ACCESS POINT WiFi6E (External Antenna...,Sustaining,2024Q4,522.0,287.0,2219.0,2219.0,4,1,4657.000000,3716.543959
353,14.0,WIRELESS ACCESS POINT WiFi6E (External Antenna...,Sustaining,2025Q1,500.0,385.0,3191.0,3191.0,1,1,2913.666667,4161.555278
354,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2023Q2,40505.0,0.0,30499.0,30499.0,2,0,40505.000000,NaN
355,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2023Q3,30498.0,0.0,40505.0,40505.0,3,0,35501.500000,7076.017559
356,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2023Q4,60073.0,0.0,61214.0,61214.0,4,0,43692.000000,15042.868177
357,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2024Q1,59424.0,0.0,41932.0,41932.0,1,0,49998.333333,16890.901407
358,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2024Q2,66952.0,16192.0,59424.0,59424.0,2,1,62149.666667,4171.582953
359,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2024Q3,57131.0,6791.0,60073.0,60073.0,3,1,61169.000000,5137.779579
360,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2024Q4,41932.0,5507.0,66952.0,66952.0,4,1,55338.333333,12605.964475
361,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2025Q1,61214.0,3750.0,57131.0,57131.0,1,1,53425.666667,10161.004002
362,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2025Q2,58318.0,8384.0,78096.0,78096.0,2,1,53821.333333,10397.782905
363,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2025Q3,71494.0,31112.0,87843.0,87843.0,3,1,63675.333333,6924.259190
364,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2025Q4,87843.0,9042.0,71494.0,71494.0,4,1,72551.666667,14790.889099
365,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2026Q1,78096.0,9937.0,58318.0,58318.0,1,1,79144.333333,8224.761537

In [395]:
df_master.shape

(366, 12)

In [396]:
df_master.shape

(366, 12)

In [398]:
df_master = df_master.sort_values(by=["cost_rank", "product", "quarter"])

In [400]:
df_master["rolling_std_3"] = df_master["rolling_std_3"].fillna(0)

In [401]:
df_master.head(10)

,cost_rank,product,life_cycle,quarter,bookings,big_deal,scms,vms,quarter_num,has_bigdeal,rolling_mean_3,rolling_std_3
243,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q2,21149.0,0.0,21147.0,21147.0,2,0,21149.000000,0.000000
244,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q3,10584.0,0.0,10587.0,10587.0,3,0,15866.500000,7470.583143
245,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q4,16105.0,0.0,16100.0,16100.0,4,0,15946.000000,5284.294371
246,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q1,12434.0,0.0,12433.0,12433.0,1,0,13041.000000,2810.106226
247,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q2,9437.0,350.0,9440.0,9440.0,2,1,12658.666667,3339.672489
248,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q3,17530.0,1334.0,17528.0,17528.0,3,1,13133.666667,4091.614881
249,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q4,18518.0,2319.0,18524.0,18524.0,4,1,15161.666667,4982.257755
250,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2025Q1,14710.0,914.0,14707.0,14707.0,1,1,16919.333333,1976.082319
251,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2025Q2,18663.0,1950.0,16258.0,16258.0,2,1,17297.000000,2241.580469
252,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2025Q3,13144.0,902.0,14395.0,14395.0,3,1,15505.666667,2844.231765

In [402]:
df_master.tail(5)

,cost_rank,product,life_cycle,quarter,bookings,big_deal,scms,vms,quarter_num,has_bigdeal,rolling_mean_3,rolling_std_3
54,30.0,ROUTER Branch 8-Port PoE,Sustaining,None,2364.000000,0.0,0.0,0.0,<NA>,0,1207.923518,1182.442370
55,30.0,ROUTER Branch 8-Port PoE,Sustaining,None,381.000000,0.0,0.0,0.0,<NA>,0,915.256851,1268.970504
56,30.0,ROUTER Branch 8-Port PoE,0.68957,None,-0.229446,0.0,0.0,0.0,<NA>,0,914.923518,1269.330910
57,30.0,ROUTER Branch 8-Port PoE,0.68957,None,0.310430,0.0,0.0,0.0,<NA>,0,127.026995,219.947240
58,30.0,ROUTER Branch 8-Port PoE,Sustaining,None,1013.000000,0.0,0.0,0.0,<NA>,0,337.693662,584.832507

In [403]:
df_master.shape

(366, 12)

In [268]:
#scms ratio

In [404]:
df_master["scms_ratio"] = df_master["scms"] / (df_master["bookings"] + 1)

In [405]:
#vms ratio

In [406]:
df_master["vms_ratio"] = df_master["vms"] / (df_master["bookings"] + 1)

In [407]:
df_master["bigdeal_scms"] = df_master["big_deal"] * df_master["scms"]

In [409]:
df_master["bigdeal_ratio"] = df_master["big_deal"] / (df_master["bookings"] + 1)

In [410]:
 df_master["scms_pressure"] = df_master["scms"] / (df_master["bookings"] + 1)

In [411]:
df_master["vms_intensity"] = df_master["vms"] / (df_master["bookings"] + 1)

In [282]:
#product behaviour

In [412]:
df_master["product_avg"] = df_master.groupby("cost_rank")["bookings"].transform("mean")

In [413]:
df_master["deviation"] = df_master["bookings"] - df_master["product_avg"]

In [414]:
df_master["scms_vms"] = df_master["scms"] * df_master["vms"]

In [415]:
df_master.shape

(366, 21)

In [416]:
# base forecasting - time series

In [417]:
pip install statsmodels prophet

Requirement already satisfied: statsmodels in c:\users\isha\anaconda3\lib\site-packages (0.14.4)
Requirement already satisfied: prophet in c:\users\isha\anaconda3\lib\site-packages (1.3.0)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\isha\appdata\roaming\python\python313\site-packages (from statsmodels) (2.2.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\isha\appdata\roaming\python\python313\site-packages (from statsmodels) (1.15.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\isha\appdata\roaming\python\python313\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy>=0.5.6 in c:\users\isha\anaconda3\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in c:\users\isha\appdata\roaming\python\python313\site-packages (from statsmodels) (24.2)
Requirement already satisfied: cmdstanpy>=1.0.4 in c:\users\isha\anaconda3\lib\site-packages (from prophet) (1.3.0)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\isha\appdata\roaming\python\python313\site-packages (from prophet) (3.10.0)
Requirement already satisfied: holidays<1,>=0.25 in c:\users\isha\anaconda3\lib\site-packages (from prophet) (0.93)
Requirement already satisfied: tqdm>=4.36.1 in c:\users\isha\appdata\roaming\python\python313\site-packages (from prophet) (4.67.1)
Requirement already satisfied: importlib_resources in c:\users\isha\anaconda3\lib\site-packages (from prophet) (6.5.2)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in c:\users\isha\anaconda3\lib\site-packages (from cmdstanpy>=1.0.4->prophet) (0.5.1)
Requirement already satisfied: python-dateutil<3,>=2.9.0.post0 in c:\users\isha\appdata\roaming\python\python313\site-packages (from holidays<1,>=0.25->prophet) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\isha\appdata\roaming\python\python313\site-packages (from matplotlib>=2.0.0->prophet) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\isha\appdata\roaming\python\python313\site-packages (from matplotlib>=2.0.0->prophet) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\isha\appdata\roaming\python\python313\site-packages (from matplotlib>=2.0.0->prophet) (4.55.8)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\isha\appdata\roaming\python\python313\site-packages (from matplotlib>=2.0.0->prophet) (1.4.8)
Requirement already satisfied: pillow>=8 in c:\users\isha\appdata\roaming\python\python313\site-packages (from matplotlib>=2.0.0->prophet) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\isha\appdata\roaming\python\python313\site-packages (from matplotlib>=2.0.0->prophet) (3.2.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\isha\appdata\roaming\python\python313\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\isha\appdata\roaming\python\python313\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.1)
Requirement already satisfied: colorama in c:\users\isha\appdata\roaming\python\python313\site-packages (from tqdm>=4.36.1->prophet) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\isha\appdata\roaming\python\python313\site-packages (from python-dateutil<3,>=2.9.0.post0->holidays<1,>=0.25->prophet) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [418]:
from statsmodels.tsa.statespace.sarimax import SARIMAX

def sarima_forecast(df, product_id):
    
    # Filter one product
    temp = df[df["cost_rank"] == product_id].copy()
    temp = temp.sort_values("quarter")

    y = temp["bookings"].values

    # SARIMA model (simple version)
    model = SARIMAX(y, order=(1,1,0), seasonal_order=(0,0,0,0))
    model_fit = model.fit(disp=False)

    forecast = model_fit.forecast(steps=1)

    return forecast[0]

In [419]:
print(sarima_forecast(df_master,1))

15347.851380140259

In [420]:
# basline model 2 - moving average

In [421]:
def moving_avg_forecast(df, product_id):
    
    temp = df[df["cost_rank"] == product_id].copy()
    temp = temp.sort_values("quarter")

    return temp["bookings"].tail(4).mean()

In [422]:
print(moving_avg_forecast(df_master,1))

15614.5

In [423]:
# baseline model 3- naive forecast

In [424]:
def naive_forecast(df, product_id):
    
    temp = df[df["cost_rank"] == product_id].copy()
    temp = temp.sort_values("quarter")

    return temp["bookings"].iloc[-1]

In [425]:
print(naive_forecast(df_master,1))

14395.0

In [426]:
# combining Sarima, Moving Average and Naive forecast for all products (baseline forecast of all products)

In [427]:
results = []

products = df_master["cost_rank"].unique()

for p in products:
    
    # SARIMA (with error handling)
    try:
        sarima_pred = sarima_forecast(df_master, p)
    except:
        sarima_pred = None

    # Moving Average
    try:
        moving_avg_pred = moving_avg_forecast(df_master, p)
    except:
        moving_avg_pred = None

    # Naive (last value)
    try:
        naive_pred = naive_forecast(df_master, p)
    except:
        naive_pred = None

    results.append({
        "cost_rank": p,
        "sarima": sarima_pred,
        "moving_avg": moving_avg_pred,
        "naive": naive_pred
    })

df_predictions = pd.DataFrame(results)

print(df_predictions.head())

   cost_rank        sarima  moving_avg    naive
0        1.0  15347.851380    15614.50  14395.0
1        2.0  80602.871640    73937.75  78096.0
2        3.0   4648.033690     4794.75   4573.0
3        4.0   9068.201266     9069.75   8461.0
4        5.0  54041.535856    56699.00  53245.0

In [428]:
df_predictions = df_predictions.round(2)

In [429]:
print(df_predictions.head())

   cost_rank    sarima  moving_avg    naive
0        1.0  15347.85    15614.50  14395.0
1        2.0  80602.87    73937.75  78096.0
2        3.0   4648.03     4794.75   4573.0
3        4.0   9068.20     9069.75   8461.0
4        5.0  54041.54    56699.00  53245.0

In [430]:
df_predictions = df_predictions.sort_values("cost_rank")

In [431]:
df_predictions.head()

   cost_rank    sarima  moving_avg    naive
0        1.0  15347.85    15614.50  14395.0
1        2.0  80602.87    73937.75  78096.0
2        3.0   4648.03     4794.75   4573.0
3        4.0   9068.20     9069.75   8461.0
4        5.0  54041.54    56699.00  53245.0

In [432]:
# ML model - preparation

In [433]:
df_master.head()

,cost_rank,product,life_cycle,quarter,bookings,big_deal,scms,vms,quarter_num,has_bigdeal,...,rolling_std_3,scms_ratio,vms_ratio,bigdeal_scms,bigdeal_ratio,scms_pressure,vms_intensity,product_avg,deviation,scms_vms
243,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q2,21149.0,0.0,21147.0,21147.0,2,0,...,0.000000,0.999858,0.999858,0.0,0.000000,0.999858,0.999858,15243.75,5905.25,447195609.0
244,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q3,10584.0,0.0,10587.0,10587.0,3,0,...,7470.583143,1.000189,1.000189,0.0,0.000000,1.000189,1.000189,15243.75,-4659.75,112084569.0
245,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q4,16105.0,0.0,16100.0,16100.0,4,0,...,5284.294371,0.999627,0.999627,0.0,0.000000,0.999627,0.999627,15243.75,861.25,259210000.0
246,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q1,12434.0,0.0,12433.0,12433.0,1,0,...,2810.106226,0.999839,0.999839,0.0,0.000000,0.999839,0.999839,15243.75,-2809.75,154579489.0
247,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q2,9437.0,350.0,9440.0,9440.0,2,1,...,3339.672489,1.000212,1.000212,3304000.0,0.037084,1.000212,1.000212,15243.75,-5806.75,89113600.0

In [434]:
# Drop non-feature columns
df_ml = df_master.copy()

# Remove columns not needed for ML
df_ml = df_ml.drop(columns=["product", "quarter"])

# Target
y = df_ml["bookings"]

# Features
X = df_ml.drop(columns=["bookings"])

In [435]:
df_ml.head()

,cost_rank,life_cycle,bookings,big_deal,scms,vms,quarter_num,has_bigdeal,rolling_mean_3,rolling_std_3,scms_ratio,vms_ratio,bigdeal_scms,bigdeal_ratio,scms_pressure,vms_intensity,product_avg,deviation,scms_vms
243,1.0,Sustaining,21149.0,0.0,21147.0,21147.0,2,0,21149.000000,0.000000,0.999858,0.999858,0.0,0.000000,0.999858,0.999858,15243.75,5905.25,447195609.0
244,1.0,Sustaining,10584.0,0.0,10587.0,10587.0,3,0,15866.500000,7470.583143,1.000189,1.000189,0.0,0.000000,1.000189,1.000189,15243.75,-4659.75,112084569.0
245,1.0,Sustaining,16105.0,0.0,16100.0,16100.0,4,0,15946.000000,5284.294371,0.999627,0.999627,0.0,0.000000,0.999627,0.999627,15243.75,861.25,259210000.0
246,1.0,Sustaining,12434.0,0.0,12433.0,12433.0,1,0,13041.000000,2810.106226,0.999839,0.999839,0.0,0.000000,0.999839,0.999839,15243.75,-2809.75,154579489.0
247,1.0,Sustaining,9437.0,350.0,9440.0,9440.0,2,1,12658.666667,3339.672489,1.000212,1.000212,3304000.0,0.037084,1.000212,1.000212,15243.75,-5806.75,89113600.0

In [436]:
# train test split time based

In [439]:
# keep last quarter for testing 

df_ml = df_master.copy()
df_ml = df_ml.sort_values(["cost_rank", "quarter"])

In [441]:
df_ml["quarter"].isna().sum()

np.int64(0)

In [442]:
df_ml[df_ml["quarter"].isna()]

Empty DataFrame
Columns: [cost_rank, product, life_cycle, quarter, bookings, big_deal, scms, vms, quarter_num, has_bigdeal, rolling_mean_3, rolling_std_3, scms_ratio, vms_ratio, bigdeal_scms, bigdeal_ratio, scms_pressure, vms_intensity, product_avg, deviation, scms_vms]
Index: []

[0 rows x 21 columns]

In [443]:
df_ml["quarter"].value_counts(dropna=False)

quarter
2023Q2    30
2023Q3    30
2023Q4    30
2024Q1    30
2024Q2    30
2024Q3    30
2024Q4    29
2025Q1    29
2025Q2    28
2025Q3    28
2025Q4    26
2026Q1    26
None      20
Name: count, dtype: int64

In [444]:
import numpy as np

# Step 1: Convert to string and clean spaces
df_ml["quarter"] = df_ml["quarter"].astype(str).str.strip()

# Step 2: Replace "None" (string) with actual NaN
df_ml["quarter"] = df_ml["quarter"].replace("None", np.nan)

# Step 3: Drop those rows
df_ml = df_ml.dropna(subset=["quarter"]).reset_index(drop=True)

In [445]:
last_quarter = df_ml["quarter"].max()
print("Last quarter:", last_quarter)

Last quarter: 2026Q1

In [451]:
df_ml.shape

(346, 21)

In [447]:
X.head()

,cost_rank,life_cycle,big_deal,scms,vms,quarter_num,has_bigdeal,rolling_mean_3,rolling_std_3,scms_ratio,vms_ratio,bigdeal_scms,bigdeal_ratio,scms_pressure,vms_intensity,product_avg,deviation,scms_vms
243,1.0,Sustaining,0.0,21147.0,21147.0,2,0,21149.000000,0.000000,0.999858,0.999858,0.0,0.000000,0.999858,0.999858,15243.75,5905.25,447195609.0
244,1.0,Sustaining,0.0,10587.0,10587.0,3,0,15866.500000,7470.583143,1.000189,1.000189,0.0,0.000000,1.000189,1.000189,15243.75,-4659.75,112084569.0
245,1.0,Sustaining,0.0,16100.0,16100.0,4,0,15946.000000,5284.294371,0.999627,0.999627,0.0,0.000000,0.999627,0.999627,15243.75,861.25,259210000.0
246,1.0,Sustaining,0.0,12433.0,12433.0,1,0,13041.000000,2810.106226,0.999839,0.999839,0.0,0.000000,0.999839,0.999839,15243.75,-2809.75,154579489.0
247,1.0,Sustaining,350.0,9440.0,9440.0,2,1,12658.666667,3339.672489,1.000212,1.000212,3304000.0,0.037084,1.000212,1.000212,15243.75,-5806.75,89113600.0

In [448]:
df_master.head(60)

,cost_rank,product,life_cycle,quarter,bookings,big_deal,scms,vms,quarter_num,has_bigdeal,...,rolling_std_3,scms_ratio,vms_ratio,bigdeal_scms,bigdeal_ratio,scms_pressure,vms_intensity,product_avg,deviation,scms_vms
243,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q2,21149.0,0.0,21147.0,21147.0,2,0,...,0.000000,0.999858,0.999858,0.000000e+00,0.000000,0.999858,0.999858,15243.750000,5905.250000,4.471956e+08
244,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q3,10584.0,0.0,10587.0,10587.0,3,0,...,7470.583143,1.000189,1.000189,0.000000e+00,0.000000,1.000189,1.000189,15243.750000,-4659.750000,1.120846e+08
245,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q4,16105.0,0.0,16100.0,16100.0,4,0,...,5284.294371,0.999627,0.999627,0.000000e+00,0.000000,0.999627,0.999627,15243.750000,861.250000,2.592100e+08
246,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q1,12434.0,0.0,12433.0,12433.0,1,0,...,2810.106226,0.999839,0.999839,0.000000e+00,0.000000,0.999839,0.999839,15243.750000,-2809.750000,1.545795e+08
247,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q2,9437.0,350.0,9440.0,9440.0,2,1,...,3339.672489,1.000212,1.000212,3.304000e+06,0.037084,1.000212,1.000212,15243.750000,-5806.750000,8.911360e+07
248,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q3,17530.0,1334.0,17528.0,17528.0,3,1,...,4091.614881,0.999829,0.999829,2.338235e+07,0.076094,0.999829,0.999829,15243.750000,2286.250000,3.072308e+08
249,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q4,18518.0,2319.0,18524.0,18524.0,4,1,...,4982.257755,1.000270,1.000270,4.295716e+07,0.125223,1.000270,1.000270,15243.750000,3274.250000,3.431386e+08
250,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2025Q1,14710.0,914.0,14707.0,14707.0,1,1,...,1976.082319,0.999728,0.999728,1.344220e+07,0.062130,0.999728,0.999728,15243.750000,-533.750000,2.162958e+08
251,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2025Q2,18663.0,1950.0,16258.0,16258.0,2,1,...,2241.580469,0.871089,0.871089,3.170310e+07,0.104479,0.871089,0.871089,15243.750000,3419.250000,2.643226e+08
252,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2025Q3,13144.0,902.0,14395.0,14395.0,3,1,...,2844.231765,1.095093,1.095093,1.298429e+07,0.068619,1.095093,1.095093,15243.750000,-2099.750000,2.072160e+08
253,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2025Q4,16256.0,742.0,18663.0,18663.0,4,1,...,2766.994579,1.147998,1.147998,1.384795e+07,0.045642,1.147998,1.147998,15243.750000,1012.250000,3.483076e+08
254,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2026Q1,14395.0,643.0,13145.0,13145.0,1,1,...,1565.932417,0.913101,0.913101,8.452235e+06,0.044665,0.913101,0.913101,15243.750000,-848.750000,1.727910e+08
354,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2023Q2,40505.0,0.0,30499.0,30499.0,2,0,...,0.000000,0.752950,0.752950,0.000000e+00,0.000000,0.752950,0.752950,59456.666667,-18951.666667,9.301890e+08
355,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2023Q3,30498.0,0.0,40505.0,40505.0,3,0,...,7076.017559,1.328076,1.328076,0.000000e+00,0.000000,1.328076,1.328076,59456.666667,-28958.666667,1.640655e+09
356,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2023Q4,60073.0,0.0,61214.0,61214.0,4,0,...,15042.868177,1.018977,1.018977,0.000000e+00,0.000000,1.018977,1.018977,59456.666667,616.333333,3.747154e+09
357,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2024Q1,59424.0,0.0,41932.0,41932.0,1,0,...,16890.901407,0.705629,0.705629,0.000000e+00,0.000000,0.705629,0.705629,59456.666667,-32.666667,1.758293e+09
358,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2024Q2,66952.0,16192.0,59424.0,59424.0,2,1,...,4171.582953,0.887548,0.887548,9.621934e+08,0.241841,0.887548,0.887548,59456.666667,7495.333333,3.531212e+09
359,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2024Q3,57131.0,6791.0,60073.0,60073.0,3,1,...,5137.779579,1.051477,1.051477,4.079557e+08,0.118865,1.051477,1.051477,59456.666667,-2325.666667,3.608765e+09
360,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2024Q4,41932.0,5507.0,66952.0,66952.0,4,1,...,12605.964475,1.596642,1.596642,3.687047e+08,0.131329,1.596642,1.596642,59456.666667,-17524.666667,4.482570e+09
361,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2025Q1,61214.0,3750.0,57131.0,57131.0,1,1,...,10161.004002,0.933284,0.933284,2.142412e+08,0.061259,0.933284,0.933284,59456.666667,1757.333333,3.263951e+09
362,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2025Q2,58318.0,8384.0,78096.0,78096.0,2,1,...,10397.782905,1.339118,1.339118,6.547569e+08,0.143761,1.339118,1.339118,59456.666667,-1138.666667,6.098985e+09
363,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2025Q3,71494.0,31112.0,87843.0,87843.0,3,1,...,6924.259190,1.228659,1.228659,2.732971e+09,0.435163,1.228659,1.228659,59456.666667,12037.333333,7.716393e+09
364,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2025Q4,87843.0,9042.0,71494.0,71494.0,4,1,...,14790.889099,0.813875,0.813875,6.464487e+08,0.102932,0.813875,0.813875,59456.666667,28386.333333,5.111392e+09
365,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,Sustaining,2026Q1,78096.0,9937.0,58318.0,58318.0,1,1,...,8224.761537,0.746738,0.746738,5.795060e+08,0.127239,0.746738,0.746738,59456.666667,18639.333333,3.400989e+09
137,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2023Q2,6346.0,0.0,4678.0,4678.0,2,0,...,0.000000,0.737041,0.737041,0.000000e+00,0.000000,0.737041,0.737041,5284.583333,1061.416667,2.188368e+07
138,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2023Q3,6784.0,0.0,4395.0,4395.0,3,0,...,309.712770,0.647752,0.647752,0.000000e+00,0.000000,0.647752,0.647752,5284.583333,1499.416667,1.931602e+07
139,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2023Q4,4397.0,0.0,5061.0,5061.0,4,0,...,1270.709382,1.150750,1.150750,0.000000e+00,0.000000,1.150750,1.150750,5284.583333,-887.583333,2.561372e+07
140,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2024Q1,4680.0,0.0,4090.0,4090.0,1,0,...,1304.139180,0.873745,0.873745,0.000000e+00,0.000000,0.873745,0.873745,5284.583333,-604.583333,1.672810e+07
141,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2024Q2,4868.0,357.0,4570.0,4570.0,2,1,...,237.091403,0.938591,0.938591,1.631490e+06,0.073321,0.938591,0.938591,5284.583333,-416.583333,2.088490e+07
142,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2024Q3,5801.0,451.0,5448.0,5448.0,3,1,...,600.343513,0.938987,0.938987,2.457048e+06,0.077732,0.938987,0.938987,5284.583333,516.416667,2.968070e+07
143,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2024Q4,5659.0,378.0,5801.0,5801.0,4,1,...,502.714962,1.024912,1.024912,2.192778e+06,0.066784,1.024912,1.024912,5284.583333,374.416667,3.365160e+07
144,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2025Q1,5701.0,136.0,4868.0,4868.0,1,1,...,72.947470,0.853736,0.853736,6.620480e+05,0.023851,0.853736,0.853736,5284.583333,416.416667,2.369742e+07
145,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2025Q2,4092.0,0.0,5656.0,5656.0,2,0,...,917.072698,1.381871,1.381871,0.000000e+00,0.000000,1.381871,1.381871,5284.583333,-1192.583333,3.199034e+07
146,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2025Q3,5065.0,200.0,5701.0,5701.0,3,1,...,810.360619,1.125345,1.125345,1.140200e+06,0.039479,1.125345,1.125345,5284.583333,-219.583333,3.250140e+07
147,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2025Q4,5449.0,0.0,6784.0,6784.0,4,0,...,699.480045,1.244771,1.244771,0.000000e+00,0.000000,1.244771,1.244771,5284.583333,164.416667,4.602266e+07
148,3.0,SWITCH Core 25G/100G Fiber,Sustaining,2026Q1,4573.0,0.0,6346.0,6346.0,1,0,...,439.108187,1.387407,1.387407,0.000000e+00,0.000000,1.387407,1.387407,5284.583333,-711.583333,4.027172e+07
171,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2023Q2,10338.0,0.0,10927.0,10927.0,2,0,...,0.000000,1.056872,1.056872,0.000000e+00,0.000000,1.056872,1.056872,9793.833333,544.166667,1.193993e+08
172,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2023Q3,8433.0,0.0,8358.0,8358.0,3,0,...,1347.038418,0.990989,0.990989,0.000000e+00,0.000000,0.990989,0.990989,9793.833333,-1360.833333,6.985616e+07
173,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2023Q4,11681.0,0.0,11681.0,11681.0,4,0,...,1632.083433,0.999914,0.999914,0.000000e+00,0.000000,0.999914,0.999914,9793.833333,1887.166667,1.364458e+08
174,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2024Q1,10461.0,0.0,10461.0,10461.0,1,0,...,1640.664906,0.999904,0.999904,0.000000e+00,0.000000,0.999904,0.999904,9793.833333,667.166667,1.094325e+08
175,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2024Q2,8358.0,800.0,9702.0,9702.0,2,1,...,1680.939122,1.160665,1.160665,7.761600e+06,0.095705,1.160665,1.160665,9793.833333,-1435.833333,9.412880e+07
176,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2024Q3,10927.0,2558.0,11347.0,11347.0,3,1,...,1368.668818,1.038342,1.038342,2.902563e+07,0.234078,1.038342,1.038342,9793.833333,1133.166667,1.287544e+08
177,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2024Q4,9704.0,0.0,9946.0,9946.0,4,0,...,1284.990661,1.024833,1.024833,0.000000e+00,0.000000,1.024833,1.024833,9793.833333,-89.833333,9.892292e+07
178,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2025Q1,11345.0,0.0,8460.0,8460.0,1,0,...,852.773319,0.745637,0.745637,0.000000e+00,0.000000,0.745637,0.745637,9793.833333,1551.166667,7.157160e+07
179,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2025Q2,8436.0,911.0,8436.0,8436.0,2,1,...,1458.480145,0.999881,0.999881,7.685196e+06,0.107977,0.999881,0.999881,9793.833333,-1357.833333,7.116610e+07
180,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2025Q3,9436.0,1459.0,9437.0,9437.0,3,1,...,1477.980717,1.000000,1.000000,1.376858e+07,0.154604,1.000000,1.000000,9793.833333,-357.833333,8.905697e+07
181,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2025Q4,9946.0,0.0,10338.0,10338.0,4,0,...,768.136273,1.039308,1.039308,0.000000e+00,0.000000,1.039308,1.039308,9793.833333,152.166667,1.068742e+08
182,4.0,SWITCH Enterprise 24-Port PoE+,Sustaining,2026Q1,8461.0,335.0,8433.0,8433.0,1,1,...,754.536281,0.996573,0.996573,2.825055e+06,0.039589,0.996573,0.996573,9793.833333,-1332.833333,7.111549e+07
334,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2023Q2,41524.0,0.0,84349.0,84349.0,2,0,...,0.000000,2.031282,2.031282,0.000000e+00,0.000000,2.031282,2.031282,56437.666667,-14913.666667,7.114754e+09
335,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2023Q3,43188.0,0.0,67670.0,67670.0,3,0,...,1176.625684,1.566834,1.566834,0.000000e+00,0.000000,1.566834,1.566834,56437.666667,-13249.666667,4.579229e+09
336,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2023Q4,55237.0,0.0,55238.0,55238.0,4,0,...,7483.244239,1.000000,1.000000,0.000000e+00,0.000000,1.000000,1.000000,56437.666667,-1200.666667,3.051237e+09
337,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2024Q1,53599.0,0.0,53599.0,53599.0,1,0,...,6535.165976,0.999981,0.999981,0.000000e+00,0.000000,0.999981,0.999981,56437.666667,-2838.666667,2.872853e+09
338,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2024Q2,53108.0,14871.0,53108.0,53108.0,2,1,...,1114.806859,0.999981,0.999981,7.897691e+08,0.280009,0.999981,0.999981,56437.666667,-3329.666667,2.820460e+09
339,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2024Q3,51781.0,5872.0,51781.0,51781.0,3,1,...,940.490475,0.999981,0.999981,3.040580e+08,0.113398,0.999981,0.999981,56437.666667,-4656.666667,2.681272e+09
340,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2024Q4,84349.0,8789.0,59560.0,59560.0,4,1,...,18432.017587,0.706106,0.706106,5.234728e+08,0.104197,0.706106,0.706106,56437.666667,27911.333333,3.547394e+09
341,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2025Q1,67670.0,10896.0,53245.0,53245.0,1,1,...,16285.596837,0.786822,0.786822,5.801575e+08,0.161014,0.786822,0.786822,56437.666667,11232.333333,2.835030e+09
342,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2025Q2,60281.0,5581.0,60281.0,60281.0,2,1,...,12329.199663,0.999983,0.999983,3.364283e+08,0.092582,0.999983,0.999983,56437.666667,3843.333333,3.633799e+09
343,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2025Q3,53710.0,8547.0,53710.0,53710.0,3,1,...,6983.993151,0.999981,0.999981,4.590594e+08,0.159129,0.999981,0.999981,56437.666667,-2727.666667,2.884764e+09
344,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2025Q4,59560.0,7447.0,41524.0,41524.0,4,1,...,3603.710634,0.697168,0.697168,3.092292e+08,0.125031,0.697168,0.697168,56437.666667,3122.333333,1.724243e+09
345,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,Sustaining,2026Q1,53245.0,7523.0,43188.0,43188.0,1,1,...,3519.421117,0.811103,0.811103,3.249033e+08,0.141288,0.811103,0.811103,56437.666667,-3192.666667,1.865203e+09

In [452]:
df_ml.isna().sum()

cost_rank         0
product           0
life_cycle        0
quarter           0
bookings          0
big_deal          0
scms              0
vms               0
quarter_num       0
has_bigdeal       0
rolling_mean_3    0
rolling_std_3     0
scms_ratio        0
vms_ratio         0
bigdeal_scms      0
bigdeal_ratio     0
scms_pressure     0
vms_intensity     0
product_avg       0
deviation         0
scms_vms          0
dtype: int64

In [453]:
invalid = df_ml[~df_ml["quarter"].str.contains(r"\d{4}Q\d", na=False)]
print(invalid["quarter"].unique())

[]

In [454]:
# ==============================
# STEP 5: EXTRACT YEAR & QUARTER NUMBER
# ==============================

df_ml["year"] = df_ml["quarter"].str[:4].astype(int)
df_ml["q_num"] = df_ml["quarter"].str.extract(r'Q(\d)').astype(int)

In [455]:
# ==============================
# STEP 6: FIND LAST QUARTER
# ==============================

last_year = df_ml["year"].max()
last_q = df_ml[df_ml["year"] == last_year]["q_num"].max()

last_quarter = f"{last_year}Q{last_q}"

print("Last quarter:", last_quarter)

Last quarter: 2026Q1

In [456]:
# ==============================
# STEP 7: TRAIN-TEST SPLIT
# ==============================

train_df = df_ml[df_ml["quarter"] != last_quarter]
test_df = df_ml[df_ml["quarter"] == last_quarter]

In [457]:
# ==============================
# STEP 8: FEATURES & TARGET
# ==============================

X_train = train_df.drop(columns=["bookings"])
y_train = train_df["bookings"]

X_test = test_df.drop(columns=["bookings"])
y_test = test_df["bookings"]

In [458]:
# ==============================
# STEP 9: DROP NON-NUMERIC COLUMNS
# ==============================

cols_to_drop = ["product", "quarter", "life_cycle"]

X_train = X_train.drop(columns=cols_to_drop)
X_test = X_test.drop(columns=cols_to_drop)

In [459]:
# ==============================
# STEP 10: FINAL CLEAN (VERY IMPORTANT)
# ==============================

X_train = X_train.fillna(0)
X_test = X_test.fillna(0)

In [460]:
# ==============================
# FINAL CHECK
# ==============================

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)
print("Test quarter:", test_df["quarter"].unique())

Train shape: (320, 19)
Test shape: (26, 19)
Test quarter: ['2026Q1']

In [461]:
# linear regression

In [462]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Linear Regression MAE:", mean_absolute_error(y_test, y_pred_lr))

Linear Regression MAE: 1.3197511459741061e-11

In [463]:
# figuring out the reason for low MAE

In [465]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

# ==============================
# STEP 1: DEFINE MODEL
# ==============================

model = LinearRegression()

# ==============================
# STEP 2: TRAIN MODEL
# ==============================

model.fit(X_train, y_train)

# ==============================
# STEP 3: PREDICT
# ==============================

# Train predictions
y_train_pred = model.predict(X_train)

# Test predictions
y_test_pred = model.predict(X_test)

# ==============================
# STEP 4: CALCULATE MAE
# ==============================

train_mae = mean_absolute_error(y_train, y_train_pred)
test_mae = mean_absolute_error(y_test, y_test_pred)

# ==============================
# OUTPUT
# ==============================

print("Train MAE:", train_mae)
print("Test MAE:", test_mae)

Train MAE: 7.580742472993847e-12
Test MAE: 1.3197511459741061e-11

In [466]:
print(X_train.columns.tolist())

['cost_rank', 'big_deal', 'scms', 'vms', 'quarter_num', 'has_bigdeal', 'rolling_mean_3', 'rolling_std_3', 'scms_ratio', 'vms_ratio', 'bigdeal_scms', 'bigdeal_ratio', 'scms_pressure', 'vms_intensity', 'product_avg', 'deviation', 'scms_vms', 'year', 'q_num']

In [467]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

# ==============================
# STEP 1: REMOVE LEAKAGE FEATURES
# ==============================

cols_to_remove = [
    "rolling_mean_3",
    "rolling_std_3",
    "product_avg",
    "deviation"
]

X_train_clean = X_train.drop(columns=cols_to_remove, errors="ignore")
X_test_clean = X_test.drop(columns=cols_to_remove, errors="ignore")

# ==============================
# STEP 2: FILL NaNs (SAFE)
# ==============================

X_train_clean = X_train_clean.fillna(0)
X_test_clean = X_test_clean.fillna(0)

# ==============================
# STEP 3: TRAIN MODEL
# ==============================

model = LinearRegression()
model.fit(X_train_clean, y_train)

# ==============================
# STEP 4: PREDICT
# ==============================

y_train_pred = model.predict(X_train_clean)
y_test_pred = model.predict(X_test_clean)

# ==============================
# STEP 5: EVALUATE
# ==============================

train_mae = mean_absolute_error(y_train, y_train_pred)
test_mae = mean_absolute_error(y_test, y_test_pred)

print("Train MAE:", train_mae)
print("Test MAE:", test_mae)

Train MAE: 2038.2195356537784
Test MAE: 1946.774323300369

In [473]:
y_test_pred = np.maximum(y_test_pred, 0)

In [474]:
import pandas as pd
import numpy as np

# Create results dataframe
results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_test_pred
})

# Absolute Error
results["Error"] = abs(results["Actual"] - results["Predicted"])

# Accuracy (%)
results["Accuracy (%)"] = 100 * (1 - results["Error"] / (results["Actual"] + 1))

# Clip negative accuracy (optional)
results["Accuracy (%)"] = results["Accuracy (%)"].clip(lower=0)

print(results.head(300))

      Actual     Predicted         Error  Accuracy (%)
11   14395.0  16089.801995   1694.801995     88.227271
23   78096.0  57234.684275  20861.315725     73.287942
35    4573.0   8037.535300   3464.535300     24.255896
47    8461.0  10514.047527   2053.047527     75.738034
59   53245.0  46248.338673   6996.661327     86.859743
77    1719.0   3830.759860   2111.759860      0.000000
89    2422.0   3939.184696   1517.184696     37.384041
101   3645.0   4101.020566    456.020566     87.492579
113    532.0    476.282920     55.717080     89.546514
125    257.0    156.841125    100.158875     61.178731
137   3882.0   4753.345118    871.345118     77.560002
149    384.0    435.499080     51.499080     86.623615
169    223.0    169.730318     53.269682     76.218892
181   1104.0   1917.411693    813.411693     26.388082
193   1921.0   1822.944811     98.055189     94.898273
215   8870.0   8844.987763     25.012237     99.718045
227    127.0    245.944045    118.944045      7.074965
239    174.0      0.000000    174.000000      0.571429
251  21567.0  16751.460848   4815.539152     77.672760
263   7271.0   8474.323676   1203.323676     83.452645
275   2323.0   2327.205340      4.205340     99.819047
287   4128.0   4451.186868    323.186868     92.172757
299   1301.0   2043.011975    742.011975     43.009833
321   1184.0    715.398095    468.601905     60.455535
333    646.0      0.000000    646.000000      0.154560
345   1634.0    984.598955    649.401045     60.281282

In [475]:
print("Average Accuracy:", results["Accuracy (%)"].mean())

Average Accuracy: 61.92471049961586

In [476]:
df_master["bookings"].mean

<bound method Series.mean of 243    21149.000000
244    10584.000000
245    16105.000000
246    12434.000000
247     9437.000000
           ...
54      2364.000000
55       381.000000
56        -0.229446
57         0.310430
58      1013.000000
Name: bookings, Length: 366, dtype: float64>

In [477]:
# XG boost

In [478]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\isha\anaconda3\lib\site-packages (3.2.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in c:\users\isha\appdata\roaming\python\python313\site-packages (from xgboost) (2.2.2)
Requirement already satisfied: scipy in c:\users\isha\appdata\roaming\python\python313\site-packages (from xgboost) (1.15.1)

In [479]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=100,
    max_depth=4,
    learning_rate=0.1,
    random_state=42
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

print("XGBoost MAE:", mean_absolute_error(y_test, y_pred_xgb))

XGBoost MAE: 487.53386482825647

In [481]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error

# ==============================
# STEP 1: CREATE RESULTS TABLE
# ==============================

results_xgb = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred_xgb
})

# ==============================
# STEP 2: ERROR
# ==============================

results_xgb["Error"] = abs(results_xgb["Actual"] - results_xgb["Predicted"])

# ==============================
# STEP 3: ACCURACY (%)
# ==============================

results_xgb["Accuracy (%)"] = 100 * (
    1 - results_xgb["Error"] / (results_xgb["Actual"] + 1)
)

# Prevent negative accuracy
results_xgb["Accuracy (%)"] = results_xgb["Accuracy (%)"].clip(lower=0)

# ==============================
# STEP 4: AVERAGE ACCURACY
# ==============================

avg_accuracy_xgb = results_xgb["Accuracy (%)"].mean()

# ==============================
# OUTPUT
# ==============================

print(results_xgb.head(10))
print("\nXGBoost Average Accuracy:", avg_accuracy_xgb)

      Actual     Predicted        Error  Accuracy (%)
11   14395.0  13380.786133  1014.213867     92.954891
23   78096.0  73268.843750  4827.156250     93.819025
35    4573.0   4354.353027   218.646973     95.219786
47    8461.0   8842.311523   381.311523     95.493837
59   53245.0  54374.464844  1129.464844     97.878780
77    1719.0   1648.236206    70.763794     95.885826
89    2422.0   2519.871338    97.871338     95.960737
101   3645.0   3357.742920   287.257080     92.121309
113    532.0    484.658722    47.341278     91.117959
125    257.0    275.301392    18.301392     92.906437

XGBoost Average Accuracy: 88.74497533807244

In [482]:
from sklearn.metrics import mean_absolute_error

def evaluate_model(df, forecast_function):
    
    errors = []

    products = df["cost_rank"].unique()

    for p in products:
        
        temp = df[df["cost_rank"] == p].copy()
        temp = temp.sort_values("quarter")

        if len(temp) < 5:
            continue

        train = temp.iloc[:-1]
        test = temp.iloc[-1:]

        try:
            pred = forecast_function(train, p)
            actual = test["bookings"].values[0]

            error = abs(actual - pred)
            errors.append(error)

        except:
            continue

    return sum(errors) / len(errors)

In [488]:
# sarima , naive and moving avg codes

In [489]:
y_pred_naive = []

for product in test_df["cost_rank"].unique():
    
    train_prod = train_df[train_df["cost_rank"] == product]
    test_prod = test_df[test_df["cost_rank"] == product]
    
    if len(train_prod) > 0:
        last_value = train_prod["bookings"].iloc[-1]
        preds = [last_value] * len(test_prod)
    else:
        preds = [0] * len(test_prod)
    
    y_pred_naive.extend(preds)

y_pred_naive = np.array(y_pred_naive)

In [ ]:
#moving avg

In [490]:
y_pred_ma = []

for product in test_df["cost_rank"].unique():
    
    train_prod = train_df[train_df["cost_rank"] == product]
    test_prod = test_df[test_df["cost_rank"] == product]
    
    if len(train_prod) >= 3:
        avg = train_prod["bookings"].iloc[-3:].mean()
    elif len(train_prod) > 0:
        avg = train_prod["bookings"].mean()
    else:
        avg = 0
    
    preds = [avg] * len(test_prod)
    y_pred_ma.extend(preds)

y_pred_ma = np.array(y_pred_ma)

In [492]:
import pandas as pd
import numpy as np

def calculate_accuracy(y_true, y_pred, model_name):
    
    results = pd.DataFrame({
        "Actual": y_true,
        "Predicted": y_pred
    })
    
    # Error
    results["Error"] = abs(results["Actual"] - results["Predicted"])
    
    # Accuracy %
    results["Accuracy (%)"] = 100 * (
        1 - results["Error"] / (results["Actual"] + 1)
    )
    
    # Clip negative values
    results["Accuracy (%)"] = results["Accuracy (%)"].clip(lower=0)
    
    avg_accuracy = results["Accuracy (%)"].mean()
    
    print(f"\n{model_name} Average Accuracy:", avg_accuracy)
    
    return results, avg_accuracy

In [493]:
results_ma, avg_ma = calculate_accuracy(
    y_test, y_pred_ma, "Moving Average"
)

print(results_ma.head())

Moving Average Average Accuracy: 75.59590459715719
     Actual     Predicted        Error  Accuracy (%)
11  14395.0  16021.000000  1626.000000     88.705196
23  78096.0  72551.666667  5544.333333     92.900709
35   4573.0   4868.666667   295.666667     93.535928
47   8461.0   9272.666667   811.666667     90.408099
59  53245.0  57850.333333  4605.333333     91.350837

In [494]:
results_naive, avg_naive = calculate_accuracy(
    y_test, y_pred_naive, "Naive"
)

print(results_naive.head())

Naive Average Accuracy: 71.02470836244808
     Actual  Predicted   Error  Accuracy (%)
11  14395.0    16256.0  1861.0     87.072798
23  78096.0    87843.0  9747.0     87.519367
35   4573.0     5449.0   876.0     80.848273
47   8461.0     9946.0  1485.0     82.450957
59  53245.0    59560.0  6315.0     88.139954

In [495]:
print(df_master["bookings"].describe())

count      366.000000
mean      7381.878067
std      15148.704369
min         -0.548315
25%        500.500000
50%       1899.000000
75%       5433.750000
max      87843.000000
Name: bookings, dtype: float64

In [496]:
def evaluate_mape(df, forecast_function):
    
    errors = []

    products = df["cost_rank"].unique()

    for p in products:
        temp = df[df["cost_rank"] == p].copy()
        temp = temp.sort_values("quarter")

        if len(temp) < 5:
            continue

        train = temp.iloc[:-1]
        test = temp.iloc[-1:]

        try:
            pred = forecast_function(train, p)
            actual = test["bookings"].values[0]

            if actual != 0:
                error = abs((actual - pred) / actual)
                errors.append(error)

        except:
            continue

    return sum(errors) / len(errors) * 100

In [499]:
def weighted_moving_avg(df, product_id):
    
    temp = df[df["cost_rank"] == product_id].copy()
    temp = temp.sort_values("quarter")

    values = temp["bookings"].tail(4).values
    weights = [0.1, 0.2, 0.3, 0.4]

    return sum(v*w for v, w in zip(values, weights))

In [500]:
weighted_mape = evaluate_mape(df_master, weighted_moving_avg)

print("Weighted Moving Avg MAPE:", weighted_mape)

Weighted Moving Avg MAPE: 66.25901827272978

In [202]:
df_master.head()

,cost_rank,product,quarter,bookings,big_deal,scms,vms,quarter_num,time_index,lag_1,...,lag_4,has_bigdeal,scms_ratio,vms_ratio,bigdeal_scms,trend_vms,rolling_mean_3,rolling_std_3,growth_1,growth_4
4,1,SWITCH Enterprise 48-Port UPOE,2024Q2,9437.0,350.0,9440.0,9440.0,2,4,12434.0,...,21149.0,1,1.000212,1.000212,3304000.0,37760.0,NaN,NaN,-0.241013,-0.553759
5,1,SWITCH Enterprise 48-Port UPOE,2024Q3,17530.0,1334.0,17528.0,17528.0,3,5,9437.0,...,10584.0,1,0.999829,0.999829,23382352.0,87640.0,NaN,NaN,0.857491,0.656212
6,1,SWITCH Enterprise 48-Port UPOE,2024Q4,18518.0,2319.0,18524.0,18524.0,4,6,17530.0,...,16105.0,1,1.000270,1.000270,42957156.0,111144.0,15161.666667,4982.257755,0.056357,0.149820
7,1,SWITCH Enterprise 48-Port UPOE,2025Q1,14710.0,914.0,14707.0,14707.0,1,7,18518.0,...,12434.0,1,0.999728,0.999728,13442198.0,102949.0,16919.333333,1976.082319,-0.205627,0.183032
8,1,SWITCH Enterprise 48-Port UPOE,2025Q2,16256.0,1950.0,16258.0,16258.0,2,8,14710.0,...,9437.0,1,1.000062,1.000062,31703100.0,130064.0,16494.666667,1915.185979,0.105091,0.722505

In [503]:
df_master.describe()

,cost_rank,bookings,big_deal,scms,vms,quarter_num,has_bigdeal,rolling_mean_3,rolling_std_3,scms_ratio,vms_ratio,bigdeal_scms,bigdeal_ratio,scms_pressure,vms_intensity,product_avg,deviation,scms_vms
count,366.000000,366.000000,366.000000,366.000000,366.000000,346.0,366.000000,366.000000,366.000000,366.000000,366.000000,3.660000e+02,366.000000,366.000000,366.000000,366.000000,3.660000e+02,3.660000e+02
mean,16.363388,7381.878067,743.551913,7291.508197,7291.508197,2.5,0.366120,7321.838071,1320.810213,22.694753,22.694753,3.166766e+07,3.715728,22.694753,22.694753,7381.878067,9.722399e-14,2.829348e+08
std,9.039134,15148.704369,2583.933626,15178.872534,15178.872534,1.11186,0.482402,14518.239349,2773.651047,182.967611,182.967611,1.782619e+08,36.334462,182.967611,182.967611,14632.507994,3.920836e+03,9.797171e+08
min,1.000000,-0.548315,0.000000,0.000000,0.000000,1.0,0.000000,-0.152044,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,111.650475,-2.895867e+04,0.000000e+00
25%,9.000000,500.500000,0.000000,385.500000,385.500000,2.0,0.000000,536.500000,82.038605,0.710203,0.710203,0.000000e+00,0.000000,0.710203,0.710203,602.750000,-4.935417e+02,1.486170e+05
50%,17.000000,1899.000000,0.000000,1721.000000,1721.000000,2.5,0.000000,1838.750000,372.911209,0.996273,0.996273,0.000000e+00,0.000000,0.996273,0.996273,1776.500000,-3.454167e+01,2.961845e+06
75%,24.000000,5433.750000,257.750000,5299.750000,5299.750000,3.0,1.000000,5257.000000,942.448904,1.220740,1.220740,4.773525e+05,0.104409,1.220740,1.220740,5284.583333,3.538366e+02,2.809349e+07
max,30.000000,87843.000000,31112.000000,87843.000000,87843.000000,4.0,1.000000,79144.333333,18432.017587,2926.345455,2926.345455,2.732971e+09,445.990466,2926.345455,2926.345455,59456.666667,2.838633e+04,7.716393e+09

In [504]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\isha\anaconda3\lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\users\isha\appdata\roaming\python\python313\site-packages (from lightgbm) (2.2.2)
Requirement already satisfied: scipy in c:\users\isha\appdata\roaming\python\python313\site-packages (from lightgbm) (1.15.1)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [506]:
from lightgbm import LGBMRegressor
import numpy as np
from sklearn.metrics import mean_absolute_error

df_lgb = df_ml.copy()

# Remove non-numeric columns
cols_to_drop = ["product", "quarter", "life_cycle"]
df_lgb = df_lgb.drop(columns=cols_to_drop, errors="ignore")

# Remove leakage features
leak_cols = ["rolling_mean_3", "rolling_std_3", "product_avg", "deviation"]
df_lgb = df_lgb.drop(columns=leak_cols, errors="ignore")

# Fill NaNs
df_lgb = df_lgb.fillna(0)

In [507]:
y = np.log1p(df_lgb["bookings"])
X = df_lgb.drop(columns=["bookings"])

In [508]:
# Get last quarter
last_quarter = df_ml["quarter"].max()

train_idx = df_ml["quarter"] != last_quarter
test_idx = df_ml["quarter"] == last_quarter

X_train = X[train_idx]
X_test = X[test_idx]

y_train = y[train_idx]
y_test = y[test_idx]

In [509]:
lgb = LGBMRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    random_state=42
)

lgb.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000889 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 879
[LightGBM] [Info] Number of data points in the train set: 320, number of used features: 15
[LightGBM] [Info] Start training from score 7.419253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMRegressor(learning_rate=0.05, max_depth=5, n_estimators=200,
              random_state=42)

In [511]:
y_pred_log = lgb.predict(X_test)

y_pred = np.expm1(y_pred_log)
y_test_actual = np.expm1(y_test)

In [512]:
mae = mean_absolute_error(y_test_actual, y_pred)

print("LightGBM MAE:", mae)

LightGBM MAE: 1585.1877154015347

In [307]:
print(y_test_actual.describe())

count      45.000000
mean     1945.600000
std      1493.376412
min       155.000000
25%      1026.000000
50%      1537.000000
75%      2165.000000
max      7708.000000
Name: bookings, dtype: float64

In [ ]:
#accuracy of light bgm

In [513]:
import pandas as pd
import numpy as np

# ==============================
# STEP 1: CREATE RESULTS TABLE
# ==============================

results_lgb = pd.DataFrame({
    "Actual": y_test_actual,
    "Predicted": y_pred
})

# ==============================
# STEP 2: CALCULATE ERROR
# ==============================

results_lgb["Error"] = abs(results_lgb["Actual"] - results_lgb["Predicted"])

# ==============================
# STEP 3: CALCULATE ACCURACY (%)
# ==============================

results_lgb["Accuracy (%)"] = 100 * (
    1 - results_lgb["Error"] / (results_lgb["Actual"] + 1)
)

# Avoid negative accuracy
results_lgb["Accuracy (%)"] = results_lgb["Accuracy (%)"].clip(lower=0)

# ==============================
# STEP 4: AVERAGE ACCURACY
# ==============================

avg_accuracy_lgb = results_lgb["Accuracy (%)"].mean()

# ==============================
# OUTPUT
# ==============================

print(results_lgb.head(10))
print("\nLightGBM Average Accuracy:", avg_accuracy_lgb)

      Actual     Predicted         Error  Accuracy (%)
11   14395.0  13103.181189   1291.818811     91.026543
23   78096.0  63753.642741  14342.357259     81.635201
35    4573.0   3858.512838    714.487162     84.379380
47    8461.0   8728.767199    267.767199     96.835651
59   53245.0  62983.295024   9738.295024     81.710748
77    1719.0   2249.299581    530.299581     69.168629
89    2422.0   2497.801246     75.801246     96.871595
101   3645.0   4248.719938    603.719938     83.441582
113    532.0    503.270598     28.729402     94.609868
125    257.0    260.406996      3.406996     98.679459

LightGBM Average Accuracy: 74.67443921154567

In [514]:
#comparison

In [515]:
print("Linear Accuracy:", results["Accuracy (%)"].mean())
print("XGBoost Accuracy:", avg_accuracy_xgb)
print("LightGBM Accuracy:", avg_accuracy_lgb)

Linear Accuracy: 61.92471049961586
XGBoost Accuracy: 88.74497533807244
LightGBM Accuracy: 74.67443921154567

In [516]:
print(y_pred[:10])

[13103.18118896 63753.64274101  3858.51283809  8728.76719876
 62983.29502396  2249.29958069  2497.80124643  4248.71993845
   503.27059842   260.40699639]

In [517]:
df_ml = df_ml.drop(columns=[
    "product_avg",
    "deviation"
])

In [518]:
mape = (82.63 / df_master["bookings"].mean()) * 100
print("Approx MAPE:", mape)

Approx MAPE: 1.1193628403786837

In [ ]:
#creating df_predictions

In [528]:
feature_cols = [
    'cost_rank', 'big_deal', 'scms', 'vms', 'quarter_num', 'has_bigdeal',
    'scms_ratio', 'vms_ratio', 'bigdeal_scms', 'bigdeal_ratio',
    'scms_pressure', 'vms_intensity', 'scms_vms', 'year', 'q_num'
]

In [530]:
print("\n===== DF_ML COLUMNS =====")
print(df_ml.columns.tolist())

print("\n===== FEATURE COLS =====")
print(feature_cols)

print("\n===== X_train COLUMNS =====")
print(X_train.columns.tolist())

print("\n===== X_test COLUMNS =====")
print(X_test.columns.tolist())

print("\n===== MODELS =====")
print("Linear model:", type(model))
print("XGB model:", type(xgb))
print("LGB model:", type(lgb))

print("\n===== SAMPLE LAST ROW =====")
print(df_ml.tail(1))

print("\n===== CHECK MISSING FEATURE COLS IN DF_ML =====")
missing_cols = [col for col in feature_cols if col not in df_ml.columns]
print("Missing:", missing_cols)

print("\n===== CHECK EXTRA COLS IN DF_ML =====")
extra_cols = [col for col in df_ml.columns if col not in feature_cols]
print("Extra:", extra_cols)

===== DF_ML COLUMNS =====
['cost_rank', 'product', 'life_cycle', 'quarter', 'bookings', 'big_deal', 'scms', 'vms', 'quarter_num', 'has_bigdeal', 'rolling_mean_3', 'rolling_std_3', 'scms_ratio', 'vms_ratio', 'bigdeal_scms', 'bigdeal_ratio', 'scms_pressure', 'vms_intensity', 'scms_vms', 'year', 'q_num']

===== FEATURE COLS =====
['cost_rank', 'big_deal', 'scms', 'vms', 'quarter_num', 'has_bigdeal', 'scms_ratio', 'vms_ratio', 'bigdeal_scms', 'bigdeal_ratio', 'scms_pressure', 'vms_intensity', 'scms_vms', 'year', 'q_num']

===== X_train COLUMNS =====
['cost_rank', 'big_deal', 'scms', 'vms', 'quarter_num', 'has_bigdeal', 'scms_ratio', 'vms_ratio', 'bigdeal_scms', 'bigdeal_ratio', 'scms_pressure', 'vms_intensity', 'scms_vms', 'year', 'q_num']

===== X_test COLUMNS =====
['cost_rank', 'big_deal', 'scms', 'vms', 'quarter_num', 'has_bigdeal', 'scms_ratio', 'vms_ratio', 'bigdeal_scms', 'bigdeal_ratio', 'scms_pressure', 'vms_intensity', 'scms_vms', 'year', 'q_num']

===== MODELS =====
Linear model: <class 'statsmodels.tsa.statespace.sarimax.SARIMAX'>
XGB model: <class 'xgboost.sklearn.XGBRegressor'>
LGB model: <class 'lightgbm.sklearn.LGBMRegressor'>

===== SAMPLE LAST ROW =====
     cost_rank                   product  life_cycle quarter  bookings  \
345       30.0  ROUTER Branch 8-Port PoE  Sustaining  2026Q1    1634.0

     big_deal    scms     vms  quarter_num  has_bigdeal  ...  rolling_std_3  \
345     420.0  1208.0  1208.0            1            1  ...     869.957102

     scms_ratio  vms_ratio  bigdeal_scms  bigdeal_ratio  scms_pressure  \
345    0.738838   0.738838      507360.0       0.256881       0.738838

     vms_intensity   scms_vms  year  q_num
345       0.738838  1459264.0  2026      1

[1 rows x 21 columns]

===== CHECK MISSING FEATURE COLS IN DF_ML =====
Missing: []

===== CHECK EXTRA COLS IN DF_ML =====
Extra: ['product', 'life_cycle', 'quarter', 'bookings', 'rolling_mean_3', 'rolling_std_3']

In [531]:
#finding df_predictions_ml

In [535]:
# XGBoost features (used during training)
xgb_features = xgb.get_booster().feature_names

# LightGBM features (used during training)
lgb_features = X_train.columns   # (this is your clean dataset)

In [536]:
ml_results = []

for p in df_ml["cost_rank"].unique():
    
    temp = df_ml[df_ml["cost_rank"] == p].sort_values("quarter")
    last_row = temp.tail(1)
    
    # ==============================
    # XGBOOST INPUT
    # ==============================
    X_xgb = last_row.reindex(columns=xgb_features, fill_value=0)
    xgb_pred = xgb.predict(X_xgb)[0]
    
    # ==============================
    # LIGHTGBM INPUT
    # ==============================
    X_lgb = last_row.reindex(columns=lgb_features, fill_value=0)
    
    lgb_pred_log = lgb.predict(X_lgb)[0]
    lgb_pred = np.expm1(lgb_pred_log)
    
    # ==============================
    # STORE
    # ==============================
    ml_results.append({
        "cost_rank": p,
        "xgb_pred": xgb_pred,
        "lgb_pred": lgb_pred
    })

df_predictions_ml = pd.DataFrame(ml_results)

print(df_predictions_ml.head())

   cost_rank      xgb_pred      lgb_pred
0        1.0  11037.458008  13103.181189
1        2.0  70597.242188  63753.642741
2        3.0   4108.848633   3858.512838
3        4.0   7853.494141   8728.767199
4        5.0  58630.269531  62983.295024

In [520]:
# creating df_predictions_ml

In [537]:
import pandas as pd
import numpy as np

ts_results = []

for p in df_ml["cost_rank"].unique():
    
    # Get product-wise data (sorted properly)
    temp = df_ml[df_ml["cost_rank"] == p].sort_values("quarter")
    
    # ==============================
    # SAFE SERIES EXTRACTION
    # ==============================
    
    series = temp["bookings"].fillna(0).values
    
    # ==============================
    # NAIVE PREDICTION
    # ==============================
    
    if len(series) > 0:
        naive_pred = series[-1]   # last value
    else:
        naive_pred = 0
    
    # ==============================
    # MOVING AVERAGE (LAST 3)
    # ==============================
    
    if len(series) >= 3:
        ma_pred = np.mean(series[-3:])
    elif len(series) > 0:
        ma_pred = np.mean(series)
    else:
        ma_pred = 0
    
    # ==============================
    # STORE RESULTS
    # ==============================
    
    ts_results.append({
        "cost_rank": p,
        "naive_pred": naive_pred,
        "ma_pred": ma_pred
    })

# Final dataframe
df_predictions_ts = pd.DataFrame(ts_results)

print(df_predictions_ts.head())

   cost_rank  naive_pred       ma_pred
0        1.0     14395.0  14598.333333
1        2.0     78096.0  79144.333333
2        3.0      4573.0   5029.000000
3        4.0      8461.0   9281.000000
4        5.0     53245.0  55505.000000

In [526]:
df_ml.columns

Index(['cost_rank', 'product', 'life_cycle', 'quarter', 'bookings', 'big_deal',
       'scms', 'vms', 'quarter_num', 'has_bigdeal', 'rolling_mean_3',
       'rolling_std_3', 'scms_ratio', 'vms_ratio', 'bigdeal_scms',
       'bigdeal_ratio', 'scms_pressure', 'vms_intensity', 'scms_vms', 'year',
       'q_num'],
      dtype='object')

In [319]:
# merging df_predictions and df_predictions_ml

In [538]:
df_final = df_predictions.merge(
    df_predictions_ml,
    on="cost_rank"
)

In [539]:
df_final.head()

   cost_rank    sarima  moving_avg    naive      xgb_pred      lgb_pred
0        1.0  15347.85    15614.50  14395.0  11037.458008  13103.181189
1        2.0  80602.87    73937.75  78096.0  70597.242188  63753.642741
2        3.0   4648.03     4794.75   4573.0   4108.848633   3858.512838
3        4.0   9068.20     9069.75   8461.0   7853.494141   8728.767199
4        5.0  54041.54    56699.00  53245.0  58630.269531  62983.295024

In [540]:
# emsemble

In [543]:
acc_xgb = 88.744
acc_ma = 75.59
acc_naive = 71.02
acc_lgb = 74.67

In [544]:
total = acc_xgb + acc_ma + acc_naive + acc_lgb

w_xgb = acc_xgb / total
w_ma = acc_ma / total
w_naive = acc_naive / total
w_lgb = acc_lgb / total

print("Weights:")
print("XGB:", w_xgb)
print("MA:", w_ma)
print("Naive:", w_naive)
print("LGB:", w_lgb)

Weights:
XGB: 0.28624880654400947
MA: 0.24381983330322815
Naive: 0.22907903904213867
LGB: 0.24085232111062368

In [546]:
df_final.columns

Index(['cost_rank', 'sarima', 'moving_avg', 'naive', 'xgb_pred', 'lgb_pred'], dtype='object')

In [547]:
df_final["final_forecast"] = (
    w_xgb   * df_final["xgb_pred"] +
    w_lgb   * df_final["lgb_pred"] +
    w_ma    * df_final["moving_avg"] +
    w_naive * df_final["naive"]
)

In [548]:
df_final.head()

,cost_rank,sarima,moving_avg,naive,xgb_pred,lgb_pred,final_forecast
0,1.0,15347.85,15614.50,14395.0,11037.458008,13103.181189,13420.108386
1,2.0,80602.87,73937.75,78096.0,70597.242188,63753.642741,71481.236299
2,3.0,4648.03,4794.75,4573.0,4108.848633,3858.512838,4322.118318
3,4.0,9068.20,9069.75,8461.0,7853.494141,8728.767199,8500.019745
4,5.0,54041.54,56699.00,53245.0,58630.269531,62983.295024,57974.170710

In [549]:
df_final.head()

,cost_rank,sarima,moving_avg,naive,xgb_pred,lgb_pred,final_forecast
0,1.0,15347.85,15614.50,14395.0,11037.458008,13103.181189,13420.108386
1,2.0,80602.87,73937.75,78096.0,70597.242188,63753.642741,71481.236299
2,3.0,4648.03,4794.75,4573.0,4108.848633,3858.512838,4322.118318
3,4.0,9068.20,9069.75,8461.0,7853.494141,8728.767199,8500.019745
4,5.0,54041.54,56699.00,53245.0,58630.269531,62983.295024,57974.170710

In [550]:
df_predictions.head()

   cost_rank    sarima  moving_avg    naive
0        1.0  15347.85    15614.50  14395.0
1        2.0  80602.87    73937.75  78096.0
2        3.0   4648.03     4794.75   4573.0
3        4.0   9068.20     9069.75   8461.0
4        5.0  54041.54    56699.00  53245.0

In [551]:
df_master.head()

,cost_rank,product,life_cycle,quarter,bookings,big_deal,scms,vms,quarter_num,has_bigdeal,...,rolling_std_3,scms_ratio,vms_ratio,bigdeal_scms,bigdeal_ratio,scms_pressure,vms_intensity,product_avg,deviation,scms_vms
243,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q2,21149.0,0.0,21147.0,21147.0,2,0,...,0.000000,0.999858,0.999858,0.0,0.000000,0.999858,0.999858,15243.75,5905.25,447195609.0
244,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q3,10584.0,0.0,10587.0,10587.0,3,0,...,7470.583143,1.000189,1.000189,0.0,0.000000,1.000189,1.000189,15243.75,-4659.75,112084569.0
245,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2023Q4,16105.0,0.0,16100.0,16100.0,4,0,...,5284.294371,0.999627,0.999627,0.0,0.000000,0.999627,0.999627,15243.75,861.25,259210000.0
246,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q1,12434.0,0.0,12433.0,12433.0,1,0,...,2810.106226,0.999839,0.999839,0.0,0.000000,0.999839,0.999839,15243.75,-2809.75,154579489.0
247,1.0,SWITCH Enterprise 48-Port UPOE,Sustaining,2024Q2,9437.0,350.0,9440.0,9440.0,2,1,...,3339.672489,1.000212,1.000212,3304000.0,0.037084,1.000212,1.000212,15243.75,-5806.75,89113600.0

In [552]:
df_master.columns

Index(['cost_rank', 'product', 'life_cycle', 'quarter', 'bookings', 'big_deal',
       'scms', 'vms', 'quarter_num', 'has_bigdeal', 'rolling_mean_3',
       'rolling_std_3', 'scms_ratio', 'vms_ratio', 'bigdeal_scms',
       'bigdeal_ratio', 'scms_pressure', 'vms_intensity', 'product_avg',
       'deviation', 'scms_vms'],
      dtype='object')

In [553]:
df_final.columns

Index(['cost_rank', 'sarima', 'moving_avg', 'naive', 'xgb_pred', 'lgb_pred',
       'final_forecast'],
      dtype='object')

In [554]:
# big deal effect

In [555]:
bigdeal_prob = df_master.groupby("cost_rank")["big_deal"].apply(lambda x: (x > 0).mean()).reset_index()
bigdeal_prob.columns = ["cost_rank", "bigdeal_prob"]

In [556]:
bigdeal_avg = df_master[df_master["big_deal"] > 0].groupby("cost_rank")["big_deal"].mean().reset_index()
bigdeal_avg.columns = ["cost_rank", "avg_bigdeal"]

In [557]:
df_final = df_final.merge(bigdeal_prob, on="cost_rank", how="left")
df_final = df_final.merge(bigdeal_avg, on="cost_rank", how="left")

df_final[["bigdeal_prob", "avg_bigdeal"]] = df_final[["bigdeal_prob", "avg_bigdeal"]].fillna(0)

In [558]:
df_final["expected_bigdeal"] = df_final["bigdeal_prob"] * df_final["avg_bigdeal"]

In [559]:
df_final["forecast_after_bigdeal"] = (
    df_final["final_forecast"] + df_final["expected_bigdeal"]
)

In [560]:
df_final.head()

,cost_rank,sarima,moving_avg,naive,xgb_pred,lgb_pred,final_forecast,bigdeal_prob,avg_bigdeal,expected_bigdeal,forecast_after_bigdeal
0,1.0,15347.85,15614.50,14395.0,11037.458008,13103.181189,13420.108386,0.666667,1144.250,762.833333,14182.941719
1,2.0,80602.87,73937.75,78096.0,70597.242188,63753.642741,71481.236299,0.666667,11339.375,7559.583333,79040.819633
2,3.0,4648.03,4794.75,4573.0,4108.848633,3858.512838,4322.118318,0.416667,304.400,126.833333,4448.951652
3,4.0,9068.20,9069.75,8461.0,7853.494141,8728.767199,8500.019745,0.416667,1212.600,505.250000,9005.269745
4,5.0,54041.54,56699.00,53245.0,58630.269531,62983.295024,57974.170710,0.666667,8690.750,5793.833333,63768.004043

In [561]:
df_master.columns

Index(['cost_rank', 'product', 'life_cycle', 'quarter', 'bookings', 'big_deal',
       'scms', 'vms', 'quarter_num', 'has_bigdeal', 'rolling_mean_3',
       'rolling_std_3', 'scms_ratio', 'vms_ratio', 'bigdeal_scms',
       'bigdeal_ratio', 'scms_pressure', 'vms_intensity', 'product_avg',
       'deviation', 'scms_vms'],
      dtype='object')

In [ ]:
#final forecast code

In [563]:
df_ml = df_ml.sort_values(["cost_rank", "year", "q_num"])

In [564]:
xgb_features = xgb.get_booster().feature_names
lgb_features = X_train.columns

In [565]:
final_results = []

for p in df_ml["cost_rank"].unique():
    
    temp = df_ml[df_ml["cost_rank"] == p].sort_values(["year", "q_num"])
    
    # Latest available row (FY26Q1)
    last_row = temp.tail(1)
    
    # ==============================
    # ML MODELS
    # ==============================
    
    X_xgb = last_row.reindex(columns=xgb_features, fill_value=0)
    xgb_pred = xgb.predict(X_xgb)[0]
    
    X_lgb = last_row.reindex(columns=lgb_features, fill_value=0)
    lgb_pred = np.expm1(lgb.predict(X_lgb)[0])
    
    # ==============================
    # TIME SERIES BASELINES
    # ==============================
    
    series = temp["bookings"].fillna(0).values
    
    # Naive
    naive_pred = series[-1] if len(series) > 0 else 0
    
    # Moving Average
    if len(series) >= 3:
        ma_pred = np.mean(series[-3:])
    else:
        ma_pred = np.mean(series) if len(series) > 0 else 0
    
    # ==============================
    # ENSEMBLE (USE YOUR WEIGHTS)
    # ==============================
    
    final_pred = (
        w_xgb * xgb_pred +
        w_lgb * lgb_pred +
        w_ma * ma_pred +
        w_naive * naive_pred
    )
    
    # ==============================
    # STORE RESULT
    # ==============================
    
    final_results.append({
        "cost_rank": p,
        "forecast_quarter": "FY26Q2",
        "xgb_pred": xgb_pred,
        "lgb_pred": lgb_pred,
        "ma_pred": ma_pred,
        "naive_pred": naive_pred,
        "final_forecast": final_pred
    })

# Final dataframe
df_fy26q2_forecast = pd.DataFrame(final_results)

print(df_fy26q2_forecast.head())

   cost_rank forecast_quarter      xgb_pred      lgb_pred       ma_pred  \
0        1.0           FY26Q2  11037.458008  13103.181189  14598.333333
1        2.0           FY26Q2  70597.242188  63753.642741  79144.333333
2        3.0           FY26Q2   4108.848633   3858.512838   5029.000000
3        4.0           FY26Q2   7853.494141   8728.767199   9281.000000
4        5.0           FY26Q2  58630.269531  62983.295024  55505.000000

   naive_pred  final_forecast
0     14395.0    13172.346799
1     78096.0    72750.704580
2      4573.0     4379.233114
3      8461.0     8551.526685
4     53245.0    57683.049829

In [566]:
df_forecasts.columns

Index(['cost_rank', 'product', 'life_cycle', 'demand_forecast',
       'marketing_forecast', 'data_science_forecast'],
      dtype='object')

In [567]:
# comparing with df_forecasts

In [577]:
df_compare = df_fy26q2_forecast.merge(
    df_forecasts,
    on="cost_rank",
    how="inner"
)

print(df_compare.head())

  cost_rank forecast_quarter      xgb_pred      lgb_pred       ma_pred  \
0       1.0           FY26Q2  11037.458008  13103.181189  14598.333333
1       1.0           FY26Q2  11037.458008  13103.181189  14598.333333
2       2.0           FY26Q2  70597.242188  63753.642741  79144.333333
3       2.0           FY26Q2  70597.242188  63753.642741  79144.333333
4       3.0           FY26Q2   4108.848633   3858.512838   5029.000000

   naive_pred  final_forecast  \
0     14395.0    13172.346799
1     14395.0    13172.346799
2     78096.0    72750.704580
3     78096.0    72750.704580
4      4573.0     4379.233114

                                             product  life_cycle  \
0                     SWITCH Enterprise 48-Port UPOE  Sustaining
1                     SWITCH Enterprise 48-Port UPOE    0.819413
2  WIRELESS ACCESS POINT WiFi6E (Internal Antenna...  Sustaining
3  WIRELESS ACCESS POINT WiFi6E (Internal Antenna...    0.885387
4                         SWITCH Core 25G/100G Fiber  Sustaining

  demand_forecast marketing_forecast data_science_forecast
0    15052.101882       14795.306069               17011.0
1        0.860012           0.139988              0.975513
2         79000.0        66274.81571               79114.0
3        0.930502           0.069498              0.709836
4     6620.962605        6739.907617                7861.0

In [578]:
df_compare["diff_demand"] = abs(df_compare["final_forecast"] - df_compare["demand_forecast"])

df_compare["diff_marketing"] = abs(df_compare["final_forecast"] - df_compare["marketing_forecast"])

df_compare["diff_ds"] = abs(df_compare["final_forecast"] - df_compare["data_science_forecast"])

In [579]:
print("Avg diff vs Demand:", df_compare["diff_demand"].mean())
print("Avg diff vs Marketing:", df_compare["diff_marketing"].mean())
print("Avg diff vs Data Science:", df_compare["diff_ds"].mean())

Avg diff vs Demand: 4622.254557563766
Avg diff vs Marketing: 4658.635164910786
Avg diff vs Data Science: 4424.729803890064

In [587]:
import numpy as np

# ==============================
# SAFE PERCENTAGE DIFFERENCE
# ==============================

df_compare["pct_diff_demand"] = (
    abs(df_compare["final_forecast"] - df_compare["demand_forecast"]) 
    / (np.maximum(df_compare["demand_forecast"], df_compare["final_forecast"]) + 1)
) * 100

df_compare["pct_diff_marketing"] = (
    abs(df_compare["final_forecast"] - df_compare["marketing_forecast"]) 
    / (np.maximum(df_compare["marketing_forecast"], df_compare["final_forecast"]) + 1)
) * 100

df_compare["pct_diff_ds"] = (
    abs(df_compare["final_forecast"] - df_compare["data_science_forecast"]) 
    / (np.maximum(df_compare["data_science_forecast"], df_compare["final_forecast"]) + 1)
) * 100

# ==============================
# AVERAGE % DIFFERENCE
# ==============================

avg_demand = df_compare["pct_diff_demand"].mean()
avg_marketing = df_compare["pct_diff_marketing"].mean()
avg_ds = df_compare["pct_diff_ds"].mean()

print("Avg % Diff vs Demand:", avg_demand)
print("Avg % Diff vs Marketing:", avg_marketing)
print("Avg % Diff vs Data Science:", avg_ds)

# ==============================
# OPTIONAL: CLEAN TABLE OUTPUT
# ==============================

comparison = pd.DataFrame({
    "Comparison": ["Demand", "Marketing", "Data Science"],
    "Avg % Difference": [avg_demand, avg_marketing, avg_ds]
})

print("\nFinal Comparison Table:")
print(comparison)

Avg % Diff vs Demand: 62.991316642501
Avg % Diff vs Marketing: 66.29772840336771
Avg % Diff vs Data Science: 63.74508145456717

Final Comparison Table:
     Comparison  Avg % Difference
0        Demand         62.991317
1     Marketing         66.297728
2  Data Science         63.745081

In [588]:
df_fy26q2_forecast = df_fy26q2_forecast.merge(
    df_ml[["cost_rank", "product"]].drop_duplicates(),
    on="cost_rank",
    how="left"
)

df_fy26q2_forecast[["cost_rank", "product", "final_forecast"]].sort_values("cost_rank")

,cost_rank,product,final_forecast
0,1.0,SWITCH Enterprise 48-Port UPOE,13172.346799
1,2.0,WIRELESS ACCESS POINT WiFi6E (Internal Antenna...,72750.704580
2,3.0,SWITCH Core 25G/100G Fiber,4379.233114
3,4.0,SWITCH Enterprise 24-Port PoE+,8551.526685
4,5.0,WIRELESS ACCESS POINT WiFi6 (Internal Antenna)...,57683.049829
5,6.0,ROUTER Core Modular Chassis,647.012210
6,7.0,SWITCH Enterprise 48-Port Fiber (Non-PoE),1784.258926
7,8.0,SWITCH Enterprise 25G Fiber,2521.810795
8,9.0,SWITCH Enterprise 24-Port UPOE,3228.299228
9,10.0,ROUTER Enterprise Edge 10G/40G,484.492326
10,11.0,SECURITY FIREWALL Next-Generation_2,263.752154
11,12.0,WIRELESS ACCESS POINT WiFi6 (External Antenna)...,3984.274233
12,13.0,SWITCH Core 100G Fiber,406.095326
13,14.0,WIRELESS ACCESS POINT WiFi6E (External Antenna...,1464.805479
14,15.0,SECURITY FIREWALL Next-Generation_1,243.877994
15,16.0,SWITCH Enterprise 48-Port PoE+ with 10G Uplink,1420.396676
16,17.0,SWITCH Enterprise 24-Port PoE+ Compact,1566.304215
17,18.0,SWITCH Data Center 25G/100G Leaf,657.703216
18,19.0,WIRELESS ACCESS POINT WiFi6 (External Antenna)...,7804.872777
19,20.0,SWITCH Data Center 100G Spine,119.518102
20,21.0,SWITCH Core 100G/400G Fiber,181.147884
21,22.0,IP PHONE Enterprise Desk,18387.621614
22,23.0,ROUTER Branch 4-Port PoE,7391.287315
23,24.0,SWITCH Industrial 8-Port PoE,2078.840787
24,25.0,IP CONFERENCE PHONE,4427.574132
25,26.0,SWITCH Industrial 8-Port PoE Compact,1433.192017
26,27.0,SWITCH Industrial Managed,575.033982
27,28.0,ROUTER Edge Aggregation Fiber,1311.799653
28,29.0,SWITCH Industrial 24-Port PoE,359.572167
29,30.0,ROUTER Branch 8-Port PoE,945.272953